In [1]:
import pandas as pd
from cuotasimss import CuotasImss
from imss import CalculoIMSSObrero, CalculoIMSSPatron
from isr import ISR
from datetime import datetime
from sbc import SBC
pd.options.display.float_format = '{:,.2f}'.format

ModuleNotFoundError: No module named 'cuotasimss'

In [2]:
df = pd.read_excel('./data/plantilla_laboral2.xlsx', sheet_name='Hoja1') #2022-10-27 incremento
df.head()

   Id                            Nombre  Sueldo mensual  Vales Fecha Ingreso
0   1      Martha Rosa Alvarez Martínez       33,256.68   1500    2019-06-03
1   2  Tania Monserrat Bañuelos Murillo       25,931.50   1297    2019-06-17
2   6        Karla Berenice Cano Garcia       22,960.82   1148    2019-07-23
3   7     Jonathan Covarrubias Sustaita       21,719.58   1086    2019-03-04
4   8              Miguel Dionicio Luna       27,315.62   1366    2018-01-09

In [3]:
df['Fecha Ingreso'] = pd.to_datetime(df['Fecha Ingreso'], format='%Y-%m-%d')

In [4]:
df_fondo = df.copy(deep=True)

In [5]:
date_2022 = pd.to_datetime('2023/12/31')

In [6]:
df['SD'] = df['Sueldo mensual'].apply(lambda x: x / 30)
df['SBC'] = df.apply(lambda x: SBC.funcion_sbc(sueldo = x['Sueldo mensual'], vales = x['Vales'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df['ISR'] = (df['Sueldo mensual'] * 1).apply(lambda x: ISR.function_isr(x))
df['IMSS_Ob'] = df['SBC'].apply(lambda x: CalculoIMSSObrero.function_imss_obrero(x))
df['IMSS_Pt'] = df.apply(lambda x: CalculoIMSSPatron.function_imss_patronal(x = x['SBC'], date=date_2022 ), axis=1)
df['ISN'] = df['Sueldo mensual'] * 0.03
_isr_ = df['Sueldo mensual'].apply(lambda x: ISR.function_isr(x))
df['Neto'] = df['Sueldo mensual'] - _isr_ - df['IMSS_Ob']
df['Aguinaldo'] = df.apply(lambda x: SBC.funcion_aguinaldo(sueldo = x['Sueldo mensual'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df['Prima Vacacional'] = df.apply(lambda x: SBC.funcion_pv(sueldo = x['Sueldo mensual'], date_ingreso = x['Fecha Ingreso'], date_base = date_2022), axis=1)

In [7]:
df

,Id,Nombre,Sueldo mensual,Vales,Fecha Ingreso,SD,SBC,ISR,IMSS_Ob,IMSS_Pt,ISN,Neto,Aguinaldo,Prima Vacacional
0,1,Martha Rosa Alvarez Martínez,"33,256.68",1500,2019-06-03,"1,108.56","1,178.79","5,479.27",959.32,"6,714.35",997.70,"26,818.09","16,628.34","4,988.50"
1,2,Tania Monserrat Bañuelos Murillo,"25,931.50",1297,2019-06-17,864.38,914.56,"3,870.97",736.42,"5,321.47",777.94,"21,324.11","12,965.75","3,889.72"
2,6,Karla Berenice Cano Garcia,"22,960.82",1148,2019-07-23,765.36,806.25,"3,236.43",645.05,"4,750.47",688.82,"19,079.34","11,480.41","3,444.12"
3,7,Jonathan Covarrubias Sustaita,"21,719.58",1086,2019-03-04,723.99,762.67,"2,971.31",608.28,"4,520.71",651.59,"18,139.99","10,859.79","3,257.94"
4,8,Miguel Dionicio Luna,"27,315.62",1366,2018-01-09,910.52,966.41,"4,166.62",780.16,"5,594.78",819.47,"22,368.84","13,657.81","4,552.60"
5,9,José Manuel Franco González,"38,020.36",1500,2015-07-09,"1,267.35","1,349.53","6,599.68","1,103.36","7,614.44","1,140.61","30,317.32","19,010.18","6,970.40"
6,11,Ana Gómez Gallardo Aguilar,"82,484.32",1500,2018-02-01,"2,749.48","2,405.50","19,212.28","1,994.18","13,181.18","2,474.53","61,277.86","41,242.16","13,747.39"
7,12,Juan Manuel González Barajas,"177,157.22",1500,2018-11-05,"5,905.24","2,405.50","50,314.06","1,994.18","13,181.18","5,314.72","124,848.98","88,578.61","29,526.20"
8,13,Gerardo González Flores,"21,719.58",1086,2019-09-02,723.99,762.67,"2,971.31",608.28,"4,520.71",651.59,"18,139.99","10,859.79","3,257.94"
9,14,Mónica González Garduño,"20,481.40",1024,2018-01-24,682.71,720.12,"2,706.83",572.39,"4,296.44",614.44,"17,202.18","10,240.70","3,413.57"
10,15,Ana Paula Gout Martinez De Velasco,"47,275.96",1500,2018-09-17,"1,575.87","1,673.22","8,776.60","1,376.42","9,320.82","1,418.28","37,122.94","23,637.98","7,879.33"
11,18,Rosa Juarez Pinzon,"22,960.82",1148,2019-06-17,765.36,806.25,"3,236.43",645.05,"4,750.47",688.82,"19,079.34","11,480.41","3,444.12"
12,19,Karen Alejandra Lara Paz,"26,059.80",1303,2019-06-17,868.66,919.07,"3,898.38",740.23,"5,345.22",781.79,"21,421.19","13,029.90","3,908.97"
13,21,Adela Marín Castillo,"34,620.44",1500,2015-07-01,"1,154.01","1,229.83","5,800.02","1,002.39","6,983.47","1,038.61","27,818.03","17,310.22","6,347.08"
14,23,Samantha Itzel Martinez Narcizo,"25,931.50",1297,2019-06-17,864.38,914.56,"3,870.97",736.42,"5,321.47",777.94,"21,324.11","12,965.75","3,889.72"
15,24,Manuel Alejandro Monroy Cruz,"21,718.36",1086,2019-11-01,723.95,762.63,"2,971.04",608.25,"4,520.49",651.55,"18,139.07","10,859.18","3,257.75"
16,25,Sergio Alberto Moreno González,"27,951.88",1398,2019-06-03,931.73,988.51,"4,302.52",798.81,"5,711.27",838.56,"22,850.55","13,975.94","4,192.78"
17,26,Ricardo Neri Vázquez,"16,144.52",807,2016-01-16,538.15,568.38,"1,780.47",444.38,"3,496.51",484.34,"13,919.67","8,072.26","2,959.83"
18,27,Stephany Peniche Ake,"20,480.18",1024,2019-06-17,682.67,719.15,"2,706.57",571.58,"4,291.32",614.41,"17,202.03","10,240.09","3,072.03"
19,28,Andrés Peña Peralta,"39,985.42",1500,2015-06-01,"1,332.85","1,418.70","7,061.87","1,161.71","7,979.08","1,199.56","31,761.84","19,992.71","7,330.66"
20,29,Francisco Javier Perez Gaspar,"20,480.18",1024,2019-06-17,682.67,719.15,"2,706.57",571.58,"4,291.32",614.41,"17,202.03","10,240.09","3,072.03"
21,30,Ángel Manuel Ramírez Contreras,"30,540.14",1500,2013-11-01,"1,018.00","1,086.18","4,855.38",881.20,"6,226.19",916.20,"24,803.56","15,270.07","5,599.03"
22,31,Nayeli Melisa Rodriguez Leonardo,"29,228.38",1461,2018-11-05,974.28,"1,037.67","4,575.18",840.28,"5,970.43",876.85,"23,812.92","14,614.19","4,871.40"
23,33,Jose Maria Sandoval Torres,"22,960.82",1148,2019-06-17,765.36,806.25,"3,236.43",645.05,"4,750.47",688.82,"19,079.34","11,480.41","3,444.12"
24,35,Elias Ebeth Teco Sánchez,"38,700.42",1500,2016-06-27,"1,290.01","1,373.46","6,759.63","1,123.55","7,740.63","1,161.01","30,817.24","19,350.21","7,095.08"
25,36,María Alejandra Torres Sandoval,"35,980.22",1500,2014-01-20,"1,199.34","1,277.70","6,119.84","1,042.77","7,235.81","1,079.41","28,817.61","17,990.11","6,596.37"
26,38,Ana Norely Flores Robles,"21,098.82",1055,2020-07-13,703.29,739.90,"2,838.71",589.08,"4,400.71",632.96,"17,671.03","10,549.41","2,813.18"
27,40,Ismael Martinez Gallegos,"46,969.82",1500,2020-10-08,"1,565.66","1,658.16","8,704.60","1,363.72","9,241.45","1,409.09","36,901.50","23,484.91","6,262.64"
28,41,Margaux Andree B Jacquemin X,"27,315.62",1366,2018-01-16,910.52,966.41,"4,166.62",780.16,"5,594.78",819.47,"22,368.84","13,657.81","4,552.60"
29,42,Rogelio Cervantes Moreno,"29,228.38",1461,2019-06-16,974.28,"1,036.33","4,575.18",839.15,"5,963.37",876.85,"23,814.05","14,614.19","4,384.26"
30,43,Sarai Rosas Trujillo,"42,092.14",1500,2019-01-07,"1,403.07","1,489.03","7,557.37","1,221.05","8,349.87","1,262.76","33,313.72","21,046.07","6,313.82"
31,44,Ethel Edith Montoya Crespo,"22,960.82",1148,2019-06-17,765.36,806.25,"3,236.43",645.05,"4,750.47",688.82,"19,079.34","11,480.41","3,444.12"
32,46,Susana Garza Leon,"18,619.40",931,2021-07-01,620.65,652.11,"2,309.11",515.02,"3,937.88",558.58,"15,795.27","9,309.70","2,172.26"
33,48,Brenda Bernaldez Ruiz,"82,484.32",1500,2017-12-11,"2,749.48","2,405.50","19,212.28","1,994.18","13,181.18","2,474.53","61,277.86","41,242.16","15,122.13"
34,49,Tania Alejandra Lopez Conde Cervantes,"34,616.78",1500,2019-02-01,"1,153.89","1,226.54","5,799.16",999.61,"6,966.11","1,038.50","27,818.01","17,308.39","5,192.52"
35,50,Zurisadai Arano Rivera,"26,685.42",1334,2019-05-27,889.51,942.04,"4,032.01",759.61,"5,466.34",800.56,"21,893.80","13,342.71","4,002.81"
36,51,Maria Del Pilar Velez Jimenez,"25,442.68",1272,2020-08-01,848.09,895.23,"3,766.56",720.11,"5,219.54",763.28,"20,956.01","12,721.34","3,392.36"
37,52,Blanca Elena Leiva Lopez,"25,442.68",1272,2020-09-01,848.09,895.23,"3,766.56",720.11,"5,219.54",763.28,"20,956.01","12,721.34","3,392.36"
38,53,Ricardo Chavez Rebolledo,"29,225.34",1461,2021-09-01,974.18,"1,033.55","4,574.54",836.80,"5,948.70",876.76,"23,814.00","14,612.67","3,409.62"
39,55,Josué Leon Morales,"19,238.94",962,2022-01-16,641.30,672.92,"2,441.44",532.57,"4,047.59",577.17,"16,264.93","9,619.47","1,923.89"
40,56,Elías Trinidad Ramos Razo,"16,757.70",838,2022-02-01,558.59,586.14,"1,911.45",459.37,"3,590.12",502.73,"14,386.88","8,378.85","1,675.77"
41,57,Mariana Ramírez Castillo,"18,616.36",931,2022-02-01,620.55,651.15,"2,308.46",514.21,"3,932.80",558.49,"15,793.69","9,308.18","1,861.64"
42,58,Estela Herrera González,"56,208.08",1500,2022-02-18,"1,873.60","1,977.00","11,329.41","1,632.70","10,922.28","1,686.24","43,245.97","28,104.04","5,620.81"
43,59,Rosa Isela Gallegos Orozco,"6,306.18",263,2022-03-01,210.21,220.58,116.63,159.26,"1,641.10",189.19,"6,030.29","3,153.09",630.62
44,60,Maria Del Carmen Tamayo Sanchez Mejorada,"17,687.64",884,2022-05-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
45,61,Monica Alvarado Espindola,"17,687.64",884,2022-05-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
46,62,Dulce Nelida Martinez Ruvalcaba,"17,687.64",884,2022-06-01,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
47,63,Brenda Hernandez Jimenez,"17,687.64",884,2022-06-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
48,64,Katya Del Rocío López Ramírez,"17,687.64",884,2022-06-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
49,65,José Alfredo López Madrigal,"17,687.64",884,2022-06-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
50,66,Jesus Geovanni Ruvalcaba Mota,"17,687.64",884,2022-07-01,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
51,67,Luis Manuel Guerrero Alcantara,"21,717.75",1086,2022-08-22,723.92,759.62,"2,970.91",605.72,"4,504.68",651.53,"18,141.12","10,858.88","2,171.77"
52,68,Shaila Barradas Santiago,"18,616.36",931,2022-09-19,620.55,651.15,"2,308.46",514.21,"3,932.80",558.49,"15,793.69","9,308.18","1,861.64"
53,69,Sergio Alexis Bautista Ángeles,"31,887.16",1500,2022-12-01,"1,062.91","1,126.33","5,157.16",915.07,"6,437.80",956.61,"25,814.93","15,943.58","3,188.72"

In [8]:
incremento = 0.078

def fondo(x):
    datos = SBC()
    found = x * incremento/2
    limit = (datos._uma * 365 * 1.3) / 12
    if found < limit:
        return found
    else:
        return limit
        
def excedente_fondo(x):
    datos = SBC()
    found = x * incremento/2
    limit = (datos._uma * 365 * 1.3) / 12
    if found > limit:
        return (found - limit) * 2
    else:
        return 0

In [9]:
df_fondo['fondo_t'] = df_fondo['Sueldo mensual'].apply(lambda x: fondo(x))
df_fondo['fondo_p'] = df_fondo['Sueldo mensual'].apply(lambda x: fondo(x))
df_fondo['excedente_fondo'] = df_fondo['Sueldo mensual'].apply(lambda x: excedente_fondo(x))

In [10]:
def vales(sueldo):
    if (sueldo * 0.05) > 1500:
        return int(1500)
    else:
        return int(round(sueldo * 0.05, 0))

In [11]:
df_fondo

,Id,Nombre,Sueldo mensual,Vales,Fecha Ingreso,fondo_t,fondo_p,excedente_fondo
0,1,Martha Rosa Alvarez Martínez,"33,256.68",1500,2019-06-03,"1,297.01","1,297.01",0.00
1,2,Tania Monserrat Bañuelos Murillo,"25,931.50",1297,2019-06-17,"1,011.33","1,011.33",0.00
2,6,Karla Berenice Cano Garcia,"22,960.82",1148,2019-07-23,895.47,895.47,0.00
3,7,Jonathan Covarrubias Sustaita,"21,719.58",1086,2019-03-04,847.06,847.06,0.00
4,8,Miguel Dionicio Luna,"27,315.62",1366,2018-01-09,"1,065.31","1,065.31",0.00
5,9,José Manuel Franco González,"38,020.36",1500,2015-07-09,"1,482.79","1,482.79",0.00
6,11,Ana Gómez Gallardo Aguilar,"82,484.32",1500,2018-02-01,"3,216.89","3,216.89",0.00
7,12,Juan Manuel González Barajas,"177,157.22",1500,2018-11-05,"3,804.70","3,804.70","6,208.86"
8,13,Gerardo González Flores,"21,719.58",1086,2019-09-02,847.06,847.06,0.00
9,14,Mónica González Garduño,"20,481.40",1024,2018-01-24,798.77,798.77,0.00
10,15,Ana Paula Gout Martinez De Velasco,"47,275.96",1500,2018-09-17,"1,843.76","1,843.76",0.00
11,18,Rosa Juarez Pinzon,"22,960.82",1148,2019-06-17,895.47,895.47,0.00
12,19,Karen Alejandra Lara Paz,"26,059.80",1303,2019-06-17,"1,016.33","1,016.33",0.00
13,21,Adela Marín Castillo,"34,620.44",1500,2015-07-01,"1,350.20","1,350.20",0.00
14,23,Samantha Itzel Martinez Narcizo,"25,931.50",1297,2019-06-17,"1,011.33","1,011.33",0.00
15,24,Manuel Alejandro Monroy Cruz,"21,718.36",1086,2019-11-01,847.02,847.02,0.00
16,25,Sergio Alberto Moreno González,"27,951.88",1398,2019-06-03,"1,090.12","1,090.12",0.00
17,26,Ricardo Neri Vázquez,"16,144.52",807,2016-01-16,629.64,629.64,0.00
18,27,Stephany Peniche Ake,"20,480.18",1024,2019-06-17,798.73,798.73,0.00
19,28,Andrés Peña Peralta,"39,985.42",1500,2015-06-01,"1,559.43","1,559.43",0.00
20,29,Francisco Javier Perez Gaspar,"20,480.18",1024,2019-06-17,798.73,798.73,0.00
21,30,Ángel Manuel Ramírez Contreras,"30,540.14",1500,2013-11-01,"1,191.07","1,191.07",0.00
22,31,Nayeli Melisa Rodriguez Leonardo,"29,228.38",1461,2018-11-05,"1,139.91","1,139.91",0.00
23,33,Jose Maria Sandoval Torres,"22,960.82",1148,2019-06-17,895.47,895.47,0.00
24,35,Elias Ebeth Teco Sánchez,"38,700.42",1500,2016-06-27,"1,509.32","1,509.32",0.00
25,36,María Alejandra Torres Sandoval,"35,980.22",1500,2014-01-20,"1,403.23","1,403.23",0.00
26,38,Ana Norely Flores Robles,"21,098.82",1055,2020-07-13,822.85,822.85,0.00
27,40,Ismael Martinez Gallegos,"46,969.82",1500,2020-10-08,"1,831.82","1,831.82",0.00
28,41,Margaux Andree B Jacquemin X,"27,315.62",1366,2018-01-16,"1,065.31","1,065.31",0.00
29,42,Rogelio Cervantes Moreno,"29,228.38",1461,2019-06-16,"1,139.91","1,139.91",0.00
30,43,Sarai Rosas Trujillo,"42,092.14",1500,2019-01-07,"1,641.59","1,641.59",0.00
31,44,Ethel Edith Montoya Crespo,"22,960.82",1148,2019-06-17,895.47,895.47,0.00
32,46,Susana Garza Leon,"18,619.40",931,2021-07-01,726.16,726.16,0.00
33,48,Brenda Bernaldez Ruiz,"82,484.32",1500,2017-12-11,"3,216.89","3,216.89",0.00
34,49,Tania Alejandra Lopez Conde Cervantes,"34,616.78",1500,2019-02-01,"1,350.05","1,350.05",0.00
35,50,Zurisadai Arano Rivera,"26,685.42",1334,2019-05-27,"1,040.73","1,040.73",0.00
36,51,Maria Del Pilar Velez Jimenez,"25,442.68",1272,2020-08-01,992.26,992.26,0.00
37,52,Blanca Elena Leiva Lopez,"25,442.68",1272,2020-09-01,992.26,992.26,0.00
38,53,Ricardo Chavez Rebolledo,"29,225.34",1461,2021-09-01,"1,139.79","1,139.79",0.00
39,55,Josué Leon Morales,"19,238.94",962,2022-01-16,750.32,750.32,0.00
40,56,Elías Trinidad Ramos Razo,"16,757.70",838,2022-02-01,653.55,653.55,0.00
41,57,Mariana Ramírez Castillo,"18,616.36",931,2022-02-01,726.04,726.04,0.00
42,58,Estela Herrera González,"56,208.08",1500,2022-02-18,"2,192.12","2,192.12",0.00
43,59,Rosa Isela Gallegos Orozco,"6,306.18",263,2022-03-01,245.94,245.94,0.00
44,60,Maria Del Carmen Tamayo Sanchez Mejorada,"17,687.64",884,2022-05-16,689.82,689.82,0.00
45,61,Monica Alvarado Espindola,"17,687.64",884,2022-05-16,689.82,689.82,0.00
46,62,Dulce Nelida Martinez Ruvalcaba,"17,687.64",884,2022-06-01,689.82,689.82,0.00
47,63,Brenda Hernandez Jimenez,"17,687.64",884,2022-06-16,689.82,689.82,0.00
48,64,Katya Del Rocío López Ramírez,"17,687.64",884,2022-06-16,689.82,689.82,0.00
49,65,José Alfredo López Madrigal,"17,687.64",884,2022-06-16,689.82,689.82,0.00
50,66,Jesus Geovanni Ruvalcaba Mota,"17,687.64",884,2022-07-01,689.82,689.82,0.00
51,67,Luis Manuel Guerrero Alcantara,"21,717.75",1086,2022-08-22,846.99,846.99,0.00
52,68,Shaila Barradas Santiago,"18,616.36",931,2022-09-19,726.04,726.04,0.00
53,69,Sergio Alexis Bautista Ángeles,"31,887.16",1500,2022-12-01,"1,243.60","1,243.60",0.00

In [12]:
_base = df_fondo['Sueldo mensual'] + df_fondo['fondo_t'] + df_fondo['excedente_fondo']

In [13]:
df_fondo['Vales'] = _base.apply(lambda x: vales(x))

In [14]:
df_fondo['SD'] = _base.apply(lambda x: x / 30)
df_fondo['SBC'] = df_fondo.apply(lambda x: SBC.funcion_sbc(sueldo = x['Sueldo mensual'] + x['fondo_t'] + x['excedente_fondo'], vales = x['Vales'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df_fondo['ISR'] = _base.apply(lambda x: ISR.function_isr(x))
df_fondo['IMSS_Ob'] = df_fondo['SBC'].apply(lambda x: CalculoIMSSObrero.function_imss_obrero(x))
df_fondo['IMSS_Pt'] = df_fondo.apply(lambda x: CalculoIMSSPatron.function_imss_patronal(x = x['SBC'], date=date_2022 ), axis=1)
df_fondo['ISN'] = _base.apply(lambda x: x * 0.03)
_isr_ = _base.apply(lambda x: ISR.function_isr(x))
df_fondo['Neto'] = df_fondo['Sueldo mensual'] - _isr_ - df_fondo['IMSS_Ob']
df_fondo['Aguinaldo'] = df_fondo.apply(lambda x: SBC.funcion_aguinaldo(sueldo = x['Sueldo mensual'] + x['fondo_t'] + x['excedente_fondo'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df_fondo['Prima Vacacional'] = df_fondo.apply(lambda x: SBC.funcion_pv(sueldo = x['Sueldo mensual'] + x['fondo_t'] + x['excedente_fondo'], date_ingreso = x['Fecha Ingreso'], date_base = date_2022), axis=1)
df_fondo['Dias Vacaciones'] = df_fondo.apply(lambda x: SBC.funcion_dias_vacaciones( date_ingreso = x['Fecha Ingreso'], date_base = date_2022), axis=1)

df_fondo['Sueldo'] = df_fondo['Sueldo mensual'] + df_fondo['fondo_t'] + df_fondo['excedente_fondo']

isr_quincena = df_fondo['Sueldo mensual'].apply(lambda x: ISR.function_isr(x))

df_fondo['ISR quincena 1'] = isr_quincena.apply(lambda x: x/2)
df_fondo['ISR quincena 2'] = df_fondo['ISR'] - df_fondo['ISR quincena 1']


# df_fondo['Porcentaje'] = ((df_fondo['Sueldo'] + df_fondo['fondo_p']) - df_fondo['Sueldo mensual'])/df_fondo['Sueldo mensual']
# df_fondo['Porcentaje2'] = ((df_fondo['Sueldo']) - df_fondo['Sueldo mensual'])/df_fondo['Sueldo mensual']

In [15]:
df_fondo

,Id,Nombre,Sueldo mensual,Vales,Fecha Ingreso,fondo_t,fondo_p,excedente_fondo,SD,SBC,...,IMSS_Ob,IMSS_Pt,ISN,Neto,Aguinaldo,Prima Vacacional,Dias Vacaciones,Sueldo,ISR quincena 1,ISR quincena 2
0,1,Martha Rosa Alvarez Martínez,"33,256.68",1500,2019-06-03,"1,297.01","1,297.01",0.00,"1,151.79","1,224.32",...,997.73,"6,954.40","1,036.61","26,474.63","17,276.85","5,183.05",18,"34,553.69","2,739.64","3,044.68"
1,2,Tania Monserrat Bañuelos Murillo,"25,931.50",1347,2019-06-17,"1,011.33","1,011.33",0.00,898.09,952.07,...,768.07,"5,519.21",808.28,"21,076.44","13,471.41","4,041.42",18,"26,942.83","1,935.48","2,151.51"
2,6,Karla Berenice Cano Garcia,"22,960.82",1193,2019-07-23,895.47,895.47,0.00,795.21,838.69,...,672.42,"4,921.49",715.69,"18,860.69","11,928.15","3,578.44",18,"23,856.29","1,618.21","1,809.50"
3,7,Jonathan Covarrubias Sustaita,"21,719.58",1128,2019-03-04,847.06,847.06,0.00,752.22,792.40,...,633.37,"4,677.46",677.00,"17,933.97","11,283.32","3,385.00",18,"22,566.64","1,485.65","1,666.58"
4,8,Miguel Dionicio Luna,"27,315.62",1419,2018-01-09,"1,065.31","1,065.31",0.00,946.03,"1,005.87",...,813.45,"5,802.80",851.43,"22,108.00","14,190.46","4,730.15",20,"28,380.93","2,083.31","2,310.86"
5,9,José Manuel Franco González,"38,020.36",1500,2015-07-09,"1,482.79","1,482.79",0.00,"1,316.77","1,401.72",...,"1,147.39","7,889.60","1,185.09","29,924.53","19,751.58","7,242.24",22,"39,503.15","3,299.84","3,648.60"
6,11,Ana Gómez Gallardo Aguilar,"82,484.32",1500,2018-02-01,"3,216.89","3,216.89",0.00,"2,856.71","2,405.50",...,"1,994.18","13,181.18","2,571.04","60,312.79","42,850.60","14,283.53",20,"85,701.21","9,606.14","10,571.21"
7,12,Juan Manuel González Barajas,"177,157.22",1500,2018-11-05,"3,804.70","3,804.70","6,208.86","6,239.03","2,405.50",...,"1,994.18","13,181.18","5,615.12","121,444.36","93,585.39","31,195.13",20,"187,170.78","25,157.03","28,561.65"
8,13,Gerardo González Flores,"21,719.58",1128,2019-09-02,847.06,847.06,0.00,752.22,792.40,...,633.37,"4,677.46",677.00,"17,933.97","11,283.32","3,385.00",18,"22,566.64","1,485.65","1,666.58"
9,14,Mónica González Garduño,"20,481.40",1064,2018-01-24,798.77,798.77,0.00,709.34,748.21,...,596.09,"4,444.50",638.41,"17,007.86","10,640.09","3,546.70",20,"21,280.17","1,353.41","1,524.03"
10,15,Ana Paula Gout Martinez De Velasco,"47,275.96",1500,2018-09-17,"1,843.76","1,843.76",0.00,"1,637.32","1,738.04",...,"1,431.11","9,662.58","1,473.59","36,634.60","24,559.86","8,186.62",20,"49,119.72","4,388.30","4,821.95"
11,18,Rosa Juarez Pinzon,"22,960.82",1193,2019-06-17,895.47,895.47,0.00,795.21,838.69,...,672.42,"4,921.49",715.69,"18,860.69","11,928.15","3,578.44",18,"23,856.29","1,618.21","1,809.50"
12,19,Karen Alejandra Lara Paz,"26,059.80",1354,2019-06-17,"1,016.33","1,016.33",0.00,902.54,956.76,...,772.02,"5,543.89",812.28,"21,172.32","13,538.07","4,061.42",18,"27,076.13","1,949.19","2,166.27"
13,21,Adela Marín Castillo,"34,620.44",1500,2015-07-01,"1,350.20","1,350.20",0.00,"1,199.02","1,277.36",...,"1,042.48","7,234.01","1,079.12","27,460.37","17,985.32","6,594.62",22,"35,970.64","2,900.01","3,217.58"
14,23,Samantha Itzel Martinez Narcizo,"25,931.50",1347,2019-06-17,"1,011.33","1,011.33",0.00,898.09,952.07,...,768.07,"5,519.21",808.28,"21,076.44","13,471.41","4,041.42",18,"26,942.83","1,935.48","2,151.51"
15,24,Manuel Alejandro Monroy Cruz,"21,718.36",1128,2019-11-01,847.02,847.02,0.00,752.18,792.36,...,633.33,"4,677.24",676.96,"17,933.06","11,282.69","3,384.81",18,"22,565.38","1,485.52","1,666.45"
16,25,Sergio Alberto Moreno González,"27,951.88",1452,2019-06-03,"1,090.12","1,090.12",0.00,968.07,"1,028.79",...,832.78,"5,923.61",871.26,"22,583.73","14,521.00","4,356.30",18,"29,042.00","2,151.26","2,384.11"
17,26,Ricardo Neri Vázquez,"16,144.52",839,2016-01-16,629.64,629.64,0.00,559.14,590.55,...,463.09,"3,613.36",503.22,"13,766.47","8,387.08","3,075.26",22,"16,774.16",890.24,"1,024.72"
18,27,Stephany Peniche Ake,"20,480.18",1064,2019-06-17,798.73,798.73,0.00,709.30,747.19,...,595.23,"4,439.10",638.37,"17,007.77","10,639.45","3,191.84",18,"21,278.91","1,353.29","1,523.89"
19,28,Andrés Peña Peralta,"39,985.42",1500,2015-06-01,"1,559.43","1,559.43",0.00,"1,384.83","1,473.61",...,"1,208.03","8,268.55","1,246.35","31,348.75","20,772.43","7,616.56",22,"41,544.85","3,530.93","3,897.71"
20,29,Francisco Javier Perez Gaspar,"20,480.18",1064,2019-06-17,798.73,798.73,0.00,709.30,747.19,...,595.23,"4,439.10",638.37,"17,007.77","10,639.45","3,191.84",18,"21,278.91","1,353.29","1,523.89"
21,30,Ángel Manuel Ramírez Contreras,"30,540.14",1500,2013-11-01,"1,191.07","1,191.07",0.00,"1,057.71","1,128.12",...,916.58,"6,447.25",951.94,"24,503.09","15,865.60","5,817.39",22,"31,731.21","2,427.69","2,692.78"
22,31,Nayeli Melisa Rodriguez Leonardo,"29,228.38",1500,2018-11-05,"1,139.91","1,139.91",0.00,"1,012.28","1,078.75",...,874.93,"6,186.98",911.05,"23,534.78","15,184.14","5,061.38",20,"30,368.29","2,287.59","2,531.08"
23,33,Jose Maria Sandoval Torres,"22,960.82",1193,2019-06-17,895.47,895.47,0.00,795.21,838.69,...,672.42,"4,921.49",715.69,"18,860.69","11,928.15","3,578.44",18,"23,856.29","1,618.21","1,809.50"
24,35,Elias Ebeth Teco Sánchez,"38,700.42",1500,2016-06-27,"1,509.32","1,509.32",0.00,"1,340.32","1,426.60",...,"1,168.38","8,020.78","1,206.29","30,417.41","20,104.87","7,371.79",22,"40,209.74","3,379.82","3,734.82"
25,36,María Alejandra Torres Sandoval,"35,980.22",1500,2014-01-20,"1,403.23","1,403.23",0.00,"1,246.11","1,327.10",...,"1,084.44","7,496.24","1,121.50","28,445.90","18,691.72","6,853.63",22,"37,383.45","3,059.92","3,389.96"
26,38,Ana Norely Flores Robles,"21,098.82",1096,2020-07-13,822.85,822.85,0.00,730.72,768.76,...,613.43,"4,552.85",657.65,"17,470.92","10,960.84","2,922.89",16,"21,921.67","1,419.36","1,595.11"
27,40,Ismael Martinez Gallegos,"46,969.82",1500,2020-10-08,"1,831.82","1,831.82",0.00,"1,626.72","1,722.40",...,"1,417.92","9,580.11","1,464.05","36,416.46","24,400.82","6,506.89",16,"48,801.64","4,352.30","4,783.14"
28,41,Margaux Andree B Jacquemin X,"27,315.62",1419,2018-01-16,"1,065.31","1,065.31",0.00,946.03,"1,005.87",...,813.45,"5,802.80",851.43,"22,108.00","14,190.46","4,730.15",20,"28,380.93","2,083.31","2,310.86"
29,42,Rogelio Cervantes Moreno,"29,228.38",1500,2019-06-16,"1,139.91","1,139.91",0.00,"1,012.28","1,077.36",...,873.76,"6,179.65",911.05,"23,535.95","15,184.14","4,555.24",18,"30,368.29","2,287.59","2,531.08"
30,43,Sarai Rosas Trujillo,"42,092.14",1500,2019-01-07,"1,641.59","1,641.59",0.00,"1,457.79","1,546.67",...,"1,269.67","8,653.72","1,312.01","32,879.00","21,866.87","6,560.06",18,"43,733.73","3,778.68","4,164.78"
31,44,Ethel Edith Montoya Crespo,"22,960.82",1193,2019-06-17,895.47,895.47,0.00,795.21,838.69,...,672.42,"4,921.49",715.69,"18,860.69","11,928.15","3,578.44",18,"23,856.29","1,618.21","1,809.50"
32,46,Susana Garza Leon,"18,619.40",967,2021-07-01,726.16,726.16,0.00,644.85,677.53,...,536.46,"4,071.92",580.37,"15,618.73","9,672.78","2,256.98",14,"19,345.56","1,154.56","1,309.65"
33,48,Brenda Bernaldez Ruiz,"82,484.32",1500,2017-12-11,"3,216.89","3,216.89",0.00,"2,856.71","2,405.50",...,"1,994.18","13,181.18","2,571.04","60,312.79","42,850.60","15,711.89",22,"85,701.21","9,606.14","10,571.21"
34,49,Tania Alejandra Lopez Conde Cervantes,"34,616.78",1500,2019-02-01,"1,350.05","1,350.05",0.00,"1,198.89","1,273.94",...,"1,039.60","7,216.00","1,079.01","27,460.49","17,983.42","5,395.03",18,"35,966.83","2,899.58","3,217.11"
35,50,Zurisadai Arano Rivera,"26,685.42",1386,2019-05-27,"1,040.73","1,040.73",0.00,924.21,980.58,...,792.11,"5,669.45",831.78,"21,639.00","13,863.08","4,158.92",18,"27,726.15","2,016.01","2,238.31"
36,51,Maria Del Pilar Velez Jimenez,"25,442.68",1322,2020-08-01,992.26,992.26,0.00,881.16,932.03,...,751.16,"5,413.57",793.05,"20,713.01","13,217.47","3,524.66",16,"26,434.94","1,883.28","2,095.23"
37,52,Blanca Elena Leiva Lopez,"25,442.68",1322,2020-09-01,992.26,992.26,0.00,881.16,932.03,...,751.16,"5,413.57",793.05,"20,713.01","13,217.47","3,524.66",16,"26,434.94","1,883.28","2,095.23"
38,53,Ricardo Chavez Rebolledo,"29,225.34",1500,2021-09-01,"1,139.79","1,139.79",0.00,"1,012.17","1,074.48",...,871.33,"6,164.49",910.95,"23,536.02","15,182.56","3,542.60",14,"30,365.13","2,287.27","2,530.72"
39,55,Josué Leon Morales,"19,238.94",999,2022-01-16,750.32,750.32,0.00,666.31,699.17,...,554.72,"4,185.98",599.68,"16,082.51","9,994.63","1,998.93",12,"19,989.26","1,220.72","1,380.99"
40,56,Elías Trinidad Ramos Razo,"16,757.70",871,2022-02-01,653.55,653.55,0.00,580.38,609.00,...,478.65,"3,710.60",522.34,"14,228.00","8,705.63","1,741.13",12,"17,411.25",955.73,"1,095.33"
41,57,Mariana Ramírez Castillo,"18,616.36",967,2022-02-01,726.04,726.04,0.00,644.75,676.55,...,535.63,"4,066.72",580.27,"15,617.19","9,671.20","1,934.24",12,"19,342.40","1,154.23","1,309.31"
42,58,Estela Herrera González,"56,208.08",1500,2022-02-18,"2,192.12","2,192.12",0.00,"1,946.67","2,053.67",...,"1,697.38","11,326.46","1,752.01","42,523.65","29,200.10","5,840.02",12,"58,400.20","5,664.70","6,322.34"
43,59,Rosa Isela Gallegos Orozco,"6,306.18",328,2022-03-01,245.94,245.94,0.00,218.40,229.18,...,165.47,"1,681.86",196.56,"5,998.48","3,276.06",655.21,12,"6,552.12",58.31,83.91
44,60,Maria Del Carmen Tamayo Sanchez Mejorada,"17,687.64",919,2022-05-16,689.82,689.82,0.00,612.58,642.78,...,507.15,"3,888.72",551.32,"14,923.06","9,188.73","1,837.75",12,"18,377.46","1,055.04","1,202.39"
45,61,Monica Alvarado Espindola,"17,687.64",919,2022-05-16,689.82,689.82,0.00,612.58,642.78,...,507.15,"3,888.72",551.32,"14,923.06","9,188.73","1,837.75",12,"18,377.46","1,055.04","1,202.39"
46,62,Dulce Nelida Martinez Ruvalcaba,"17,687.64",919,2022-06-01,689.82,689.82,0.00,612.58,642.78,...,507.15,"3,888.72",551.32,"14,923.06","9,188.73","1,837.75",12,"18,377.46","1,055.04","1,202.39"
47,63,Brenda Hernandez Jimenez,"17,687.64",919,2022-06-16,689.82,689.82,0.00,612.58,642.78,...,507.15,"3,888.72",551.32,"14,923.06","9,188.73","1,837.75",12,"18,377.46","1,055.04","1,202.39"
48,64,Katya Del Rocío López Ramírez,"17,687.64",919,2022-06-16,689.82,689.82,0.00,612.58,642.78,...,507.15,"3,888.72",551.32,"14,923.06","9,188.73","1,837.75",12,"18,377.46","1,055.04","1,202.39"
49,65,José Alfredo López Madrigal,"17,687.64",919,2022-06-16,689.82,689.82,0.00,612.58,642.78,...,507.15,"3,888.72",551.32,"14,923.06","9,188.73","1,837.75",12,"18,377.46","1,055.04","1,202.39"
50,66,Jesus Geovanni Ruvalcaba Mota,"17,687.64",919,2022-07-01,689.82,689.82,0.00,612.58,642.78,...,507.15,"3,888.72",551.32,"14,923.06","9,188.73","1,837.75",12,"18,377.46","1,055.04","1,202.39"
51,67,Luis Manuel Guerrero Alcantara,"21,717.75",1128,2022-08-22,846.99,846.99,0.00,752.16,789.25,...,630.71,"4,660.84",676.94,"17,935.21","11,282.37","2,256.47",12,"22,564.74","1,485.45","1,666.38"
52,68,Shaila Barradas Santiago,"18,616.36",967,2022-09-19,726.04,726.04,0.00,644.75,676.55,...,535.63,"4,066.72",580.27,"15,617.19","9,671.20","1,934.24",12,"19,342.40","1,154.23","1,309.31"
53,69,Sergio Alexis Bautista Ángeles,"31,887.16",1500,2022-12-01,"1,243.60","1,243.60",0.00,"1,104.36","1,169.82",...,951.76,"6,667.07",993.92,"25,485.75","16,565.38","3,313.08",12,"33,130.76","2,578.58","2,871.07"

In [16]:
df_fondo.to_excel('./resultados/calculo_2023_fondo de ahorro_final_q.xlsx', index=False, sheet_name='Hoja1')