In [3]:
import pandas as pd
from calculadora_proyectos import Proyectos

pd.read_excel('./data/data.xlsx')

costo_proyecto = Proyectos()

costo_proyecto.clean_and_load_data('./data/data.xlsx',2)

costo_proyecto.putout_data()

E:\Cursos\z_proyectos\nomina_2\calculadora_proyectos.py:37: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataframe['suma'] = dataframe.sum(axis=1)

,date,name,sueldo,concepto_1,concepto_2,concepto_3,suma,salarioDiario,3%_nomina,Cuota_Imss,Cuotas_RCV,Infonavit,Carga_laboral,Carga_laboral_total,Sueldo_proyectado,Aguinaldo,Vacaciones,Prima_vac,3%_nomina_proyectado,Cuota_Imss_proyectado,Cuotas_RCV_proyectado,Infonavit_proyectado,Carga_laboral_proyectado,Costo_proyecto,ISR mensual,IMSS mensual,sueldo neto,ahorro
0,2013-06-01,Estefania Carolina,"$ 30,000.00",NaN,NaN,NaN,"$ 30,000.00","$ 1,036.88",$ 900.00,"$ 2,402.39","$ 1,623.33","$ 1,576.05","$ 6,501.77","$ 36,501.77","$ 60,000.00","$ 2,500.00","$ 2,302.63","$ 1,151.32","$ 1,978.62","$ 4,804.78","$ 3,246.66","$ 3,152.10","$ 13,182.16","$ 73,182.16","$ 5,031.88",$ 842.01,"$ 24,126.11","$ 8,526.11"
1,2013-06-01,Estefania Carolina,"$ 30,500.00",NaN,NaN,NaN,"$ 30,500.00","$ 1,054.16",$ 915.00,"$ 2,434.66","$ 1,650.39","$ 1,602.32","$ 6,602.36","$ 37,102.36","$ 61,000.00","$ 2,541.67","$ 2,341.01","$ 1,170.50","$ 2,011.60","$ 4,869.32","$ 3,300.77","$ 3,204.64","$ 13,386.32","$ 74,386.32","$ 5,149.48",$ 856.59,"$ 24,493.93","$ 8,733.93"
2,2013-06-01,Estefania Carolina,"$ 31,000.00",NaN,NaN,NaN,"$ 31,000.00","$ 1,071.44",$ 930.00,"$ 2,466.94","$ 1,677.44","$ 1,628.59","$ 6,702.97","$ 37,702.97","$ 62,000.00","$ 2,583.33","$ 2,379.39","$ 1,189.69","$ 2,044.57","$ 4,933.88","$ 3,354.89","$ 3,257.17","$ 13,590.51","$ 75,590.51","$ 5,267.08",$ 871.17,"$ 24,861.75","$ 8,941.75"
3,2013-06-01,Estefania Carolina,"$ 31,500.00",NaN,NaN,NaN,"$ 31,500.00","$ 1,088.72",$ 945.00,"$ 2,499.21","$ 1,704.50","$ 1,654.85","$ 6,803.56","$ 38,303.56","$ 63,000.00","$ 2,625.00","$ 2,417.76","$ 1,208.88","$ 2,077.55","$ 4,998.42","$ 3,409.00","$ 3,309.70","$ 13,794.67","$ 76,794.67","$ 5,384.68",$ 885.75,"$ 25,229.57","$ 9,149.57"
4,2013-06-01,Estefania Carolina,"$ 32,000.00",NaN,NaN,NaN,"$ 32,000.00","$ 1,106.00",$ 960.00,"$ 2,531.49","$ 1,731.55","$ 1,681.12","$ 6,904.16","$ 38,904.16","$ 64,000.00","$ 2,666.67","$ 2,456.14","$ 1,228.07","$ 2,110.53","$ 5,062.98","$ 3,463.11","$ 3,362.24","$ 13,998.85","$ 77,998.85","$ 5,502.28",$ 900.33,"$ 25,597.39","$ 9,357.39"
5,2013-06-01,Estefania Carolina,"$ 32,500.00",NaN,NaN,NaN,"$ 32,500.00","$ 1,123.28",$ 975.00,"$ 2,563.76","$ 1,758.61","$ 1,707.39","$ 7,004.76","$ 39,504.76","$ 65,000.00","$ 2,708.33","$ 2,494.52","$ 1,247.26","$ 2,143.50","$ 5,127.52","$ 3,517.22","$ 3,414.77","$ 14,203.02","$ 79,203.02","$ 5,619.88",$ 914.91,"$ 25,965.21","$ 9,565.21"
6,2013-06-01,Estefania Carolina,"$ 33,000.00",NaN,NaN,NaN,"$ 33,000.00","$ 1,140.56",$ 990.00,"$ 2,596.04","$ 1,785.66","$ 1,733.65","$ 7,105.36","$ 40,105.36","$ 66,000.00","$ 2,750.00","$ 2,532.89","$ 1,266.45","$ 2,176.48","$ 5,192.08","$ 3,571.33","$ 3,467.31","$ 14,407.20","$ 80,407.20","$ 5,737.48",$ 929.49,"$ 26,333.03","$ 9,773.03"
7,2013-06-01,Estefania Carolina,"$ 33,500.00",NaN,NaN,NaN,"$ 33,500.00","$ 1,157.84","$ 1,005.00","$ 2,628.32","$ 1,812.72","$ 1,759.92","$ 7,205.96","$ 40,705.96","$ 67,000.00","$ 2,791.67","$ 2,571.27","$ 1,285.64","$ 2,209.46","$ 5,256.64","$ 3,625.44","$ 3,519.85","$ 14,611.38","$ 81,611.38","$ 5,855.08",$ 944.06,"$ 26,700.86","$ 9,980.86"
8,2013-06-01,Estefania Carolina,"$ 34,000.00",NaN,NaN,NaN,"$ 34,000.00","$ 1,175.12","$ 1,020.00","$ 2,660.59","$ 1,839.78","$ 1,786.19","$ 7,306.56","$ 41,306.56","$ 68,000.00","$ 2,833.33","$ 2,609.65","$ 1,304.82","$ 2,242.43","$ 5,321.18","$ 3,679.55","$ 3,572.38","$ 14,815.55","$ 82,815.55","$ 5,972.68",$ 958.64,"$ 27,068.68","$ 10,188.68"
9,2013-06-01,Estefania Carolina,"$ 34,500.00",NaN,NaN,NaN,"$ 34,500.00","$ 1,192.41","$ 1,035.00","$ 2,692.87","$ 1,866.83","$ 1,812.46","$ 7,407.16","$ 41,907.16","$ 69,000.00","$ 2,875.00","$ 2,648.03","$ 1,324.01","$ 2,275.41","$ 5,385.74","$ 3,733.66","$ 3,624.91","$ 15,019.73","$ 84,019.73","$ 6,090.28",$ 973.22,"$ 27,436.50","$ 10,396.50"
10,2013-06-01,Estefania Carolina,"$ 35,000.00",NaN,NaN,NaN,"$ 35,000.00","$ 1,209.69","$ 1,050.00","$ 2,725.14","$ 1,893.89","$ 1,838.72","$ 7,507.75","$ 42,507.75","$ 70,000.00","$ 2,916.67","$ 2,686.40","$ 1,343.20","$ 2,308.39","$ 5,450.28","$ 3,787.77","$ 3,677.45","$ 15,223.89","$ 85,223.89","$ 6,207.88",$ 987.80,"$ 27,804.32","$ 10,604.32"
11,2013-06-01,Estefania Carolina,"$ 35,500.00",NaN,NaN,NaN,"$ 35,500.00","$ 1,226.97","$ 1,065.00","$ 2,757.42","$ 1,920.94","$ 1,864.99","$ 7,608.35","$ 43,108.35","$ 71,000.00","$ 2,958.33","$ 2,724.78","$ 1,362.39","$ 2,341.37","$ 5,514.84","$ 3,841.88","$ 3,729.99","$ 15,428.07","$ 86,428.07","$ 6,325.48","$ 1,002.38","$ 28,172.14","$ 10,812.14"
12,2013-06-01,Estefania Carolina,"$ 36,000.00",NaN,NaN,NaN,"$ 36,000.00","$ 1,244.25","$ 1,080.00","$ 2,789.69","$ 1,948.00","$ 1,891.26","$ 7,708.95","$ 43,708.95","$ 72,000.00","$ 3,000.00","$ 2,763.16","$ 1,381.58","$ 2,374.34","$ 5,579.38","$ 3,896.00","$ 3,782.52","$ 15,632.24","$ 87,632.24","$ 6,443.08","$ 1,016.96","$ 28,539.96","$ 11,019.96"
13,2013-06-01,Estefania Carolina,"$ 36,912.60",NaN,NaN,NaN,"$ 36,912.60","$ 1,275.79","$ 1,107.38","$ 2,848.60","$ 1,997.38","$ 1,939.20","$ 7,892.56","$ 44,805.16","$ 73,825.20","$ 3,076.05","$ 2,833.20","$ 1,416.60","$ 2,434.53","$ 5,697.20","$ 3,994.76","$ 3,878.41","$ 16,004.90","$ 89,830.10","$ 6,657.73","$ 1,043.56","$ 29,211.31","$ 11,399.28"
14,2013-06-01,Estefania Carolina,"$ 13,300.00",NaN,NaN,NaN,"$ 13,300.00",$ 459.68,$ 399.00,"$ 1,324.40",$ 719.68,$ 698.72,"$ 3,141.79","$ 16,441.79","$ 26,600.00","$ 1,108.33","$ 1,020.83",$ 510.42,$ 877.19,"$ 2,648.80","$ 1,439.35","$ 1,397.43","$ 6,362.77","$ 32,962.77","$ 1,402.52",$ 355.09,"$ 11,542.39","$ 1,286.39"