In [2]:
import pandas as pd
from calculadora_proyectos import Proyectos

pd.read_excel('./data/data.xlsx')

costo_proyecto = Proyectos()

costo_proyecto.clean_and_load_data('./data/data.xlsx',2)

costo_proyecto.putout_data()

E:\Cursos\z_proyectos\nomina_2\calculadora_proyectos.py:58: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataframe['suma'] = dataframe.sum(axis=1)

,date,name,sueldo,concepto_1,concepto_2,concepto_3,suma,salarioDiario,3%_nomina,Cuota_Imss,Cuotas_RCV,Infonavit,Carga_laboral,Carga_laboral_total,Sueldo_proyectado,Aguinaldo,Vacaciones,Prima_vac,3%_nomina_proyectado,Cuota_Imss_proyectado,Cuotas_RCV_proyectado,Infonavit_proyectado,Carga_laboral_proyectado,Costo_proyecto,Costo_nomina_mensual_fija,ISR mensual,IMSS mensual,sueldo neto
0,2022-08-01,Antes,"$ 13,238.19",NaN,NaN,NaN,"$ 13,238.19",$ 454.90,$ 397.15,"$ 1,349.78",$ 712.19,$ 691.83,"$ 3,150.95","$ 16,389.14","$ 26,476.39","$ 1,103.18",$ 435.23,$ 217.61,$ 846.97,"$ 2,699.56","$ 1,424.39","$ 1,383.66","$ 6,354.58","$ 32,830.96","$ 14,116.21","$ 1,391.44",$ 348.65,"$ 11,498.10"
1,2022-08-01,Ahora,"$ 17,871.56",NaN,NaN,NaN,"$ 17,871.56",$ 614.12,$ 536.15,"$ 1,647.14",$ 961.46,$ 933.97,"$ 4,078.72","$ 21,950.28","$ 35,743.12","$ 1,489.30",$ 587.56,$ 293.78,"$ 1,143.41","$ 3,294.28","$ 1,922.92","$ 1,867.94","$ 8,228.55","$ 43,971.67","$ 19,056.88","$ 2,376.20",$ 482.97,"$ 15,012.39"
2,2022-08-01,Futuro,"$ 19,500.00",NaN,NaN,NaN,"$ 19,500.00",$ 670.07,$ 585.00,"$ 1,751.65","$ 1,049.07","$ 1,019.07","$ 4,404.79","$ 23,904.79","$ 39,000.00","$ 1,625.00",$ 641.10,$ 320.55,"$ 1,247.60","$ 3,503.30","$ 2,098.14","$ 2,038.14","$ 8,887.18","$ 47,887.18","$ 20,793.32","$ 2,724.04",$ 530.17,"$ 16,245.79"
3,2022-08-01,Posible,"$ 21,500.00",NaN,NaN,NaN,"$ 21,500.00",$ 738.80,$ 645.00,"$ 1,880.00","$ 1,156.67","$ 1,123.59","$ 4,805.26","$ 26,305.26","$ 43,000.00","$ 1,791.67",$ 706.85,$ 353.43,"$ 1,375.56","$ 3,760.00","$ 2,313.33","$ 2,247.18","$ 9,696.07","$ 52,696.07","$ 22,925.97","$ 3,151.24",$ 588.15,"$ 17,760.61"
4,2022-08-01,Objetivo,"$ 38,000.00",NaN,NaN,NaN,"$ 38,000.00","$ 1,305.79","$ 1,140.00","$ 2,938.93","$ 2,044.34","$ 1,985.88","$ 8,109.15","$ 46,109.15","$ 76,000.00","$ 3,166.67","$ 1,249.32",$ 624.66,"$ 2,431.22","$ 5,877.86","$ 4,088.68","$ 3,971.76","$ 16,369.52","$ 92,369.52","$ 40,520.32","$ 6,913.48","$ 1,066.46","$ 30,020.06"
5,2022-08-01,conta,"$ 34,800.00",NaN,NaN,NaN,"$ 34,800.00","$ 1,195.83","$ 1,044.00","$ 2,733.56","$ 1,872.19","$ 1,818.65","$ 7,468.39","$ 42,268.39","$ 69,600.00","$ 2,900.00","$ 1,144.11",$ 572.06,"$ 2,226.49","$ 5,467.12","$ 3,744.37","$ 3,637.30","$ 15,075.27","$ 84,675.27","$ 37,108.08","$ 6,160.84",$ 973.70,"$ 27,665.46"
6,2022-08-01,Posible,"$ 20,525.00",NaN,NaN,NaN,"$ 20,525.00",$ 705.30,$ 615.75,"$ 1,817.43","$ 1,104.21","$ 1,072.64","$ 4,610.03","$ 25,135.03","$ 41,050.00","$ 1,710.42",$ 674.80,$ 337.40,"$ 1,313.18","$ 3,634.86","$ 2,208.43","$ 2,145.27","$ 9,301.74","$ 50,351.74","$ 21,886.31","$ 2,942.98",$ 559.89,"$ 17,022.13"
7,2022-08-01,Futuro,"$ 18,525.00",NaN,NaN,NaN,"$ 18,525.00",$ 636.57,$ 555.75,"$ 1,689.08",$ 996.62,$ 968.12,"$ 4,209.56","$ 22,734.56","$ 37,050.00","$ 1,543.75",$ 609.04,$ 304.52,"$ 1,185.22","$ 3,378.16","$ 1,993.23","$ 1,936.23","$ 8,492.84","$ 45,542.84","$ 19,753.66","$ 2,515.78",$ 501.91,"$ 15,507.31"
8,2022-08-01,Ahora,"$ 18,000.00",NaN,NaN,NaN,"$ 18,000.00",$ 618.53,$ 540.00,"$ 1,655.38",$ 968.37,$ 940.68,"$ 4,104.43","$ 22,104.43","$ 36,000.00","$ 1,500.00",$ 591.78,$ 295.89,"$ 1,151.63","$ 3,310.76","$ 1,936.74","$ 1,881.36","$ 8,280.49","$ 44,280.49","$ 19,193.84","$ 2,403.64",$ 486.69,"$ 15,109.67"