In [1]:
import pandas as pd
from cuotasimss import CuotasImss
from imss import CalculoIMSSObrero, CalculoIMSSPatron
from isr import ISR
from datetime import datetime
from sbc import SBC
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
df = pd.read_excel('./data/plantilla_laboral2.xlsx', sheet_name='Hoja1') #2022-10-27 incremento
df.head()

   Id                            Nombre  Sueldo mensual  Vales Fecha Ingreso
0   1      Martha Rosa Alvarez Martínez       33,256.68   1500    2019-06-03
1   2  Tania Monserrat Bañuelos Murillo       25,931.50   1297    2019-06-17
2   6        Karla Berenice Cano Garcia       22,960.82   1148    2019-07-23
3   7     Jonathan Covarrubias Sustaita       21,719.58   1086    2019-03-04
4   8              Miguel Dionicio Luna       27,315.62   1366    2018-01-09

In [3]:
df['Fecha Ingreso'] = pd.to_datetime(df['Fecha Ingreso'], format='%Y-%m-%d')

In [4]:
date_2022 = pd.to_datetime('2023/12/31')

In [5]:
df['SD'] = df['Sueldo mensual'].apply(lambda x: x / 30)
df['SBC'] = df.apply(lambda x: SBC.funcion_sbc(sueldo = x['Sueldo mensual'], vales = x['Vales'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df['ISR'] = (df['Sueldo mensual'] * 1).apply(lambda x: ISR.function_isr(x))
df['IMSS_Ob'] = df['SBC'].apply(lambda x: CalculoIMSSObrero.function_imss_obrero(x))
df['IMSS_Pt'] = df.apply(lambda x: CalculoIMSSPatron.function_imss_patronal(x = x['SBC'], date=date_2022 ), axis=1)
df['ISN'] = df['Sueldo mensual'] * 0.03
_isr_ = df['Sueldo mensual'].apply(lambda x: ISR.function_isr(x))
df['Neto'] = df['Sueldo mensual'] - _isr_ - df['IMSS_Ob']
df['Aguinaldo'] = df.apply(lambda x: SBC.funcion_aguinaldo(sueldo = x['Sueldo mensual'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df['Prima Vacacional'] = df.apply(lambda x: SBC.funcion_pv(sueldo = x['Sueldo mensual'], date_ingreso = x['Fecha Ingreso'], date_base = date_2022), axis=1)

In [6]:
df

,Id,Nombre,Sueldo mensual,Vales,Fecha Ingreso,SD,SBC,ISR,IMSS_Ob,IMSS_Pt,ISN,Neto,Aguinaldo,Prima Vacacional
0,1,Martha Rosa Alvarez Martínez,"33,256.68",1500,2019-06-03,"1,108.56","1,178.64","5,479.27",959.20,"6,713.58",997.70,"26,818.21","16,628.34","4,988.50"
1,2,Tania Monserrat Bañuelos Murillo,"25,931.50",1297,2019-06-17,864.38,914.74,"3,870.97",736.57,"5,322.38",777.94,"21,323.96","12,965.75","3,889.72"
2,6,Karla Berenice Cano Garcia,"22,960.82",1148,2019-07-23,765.36,806.25,"3,236.43",645.05,"4,750.47",688.82,"19,079.34","11,480.41","3,444.12"
3,7,Jonathan Covarrubias Sustaita,"21,719.58",1086,2019-03-04,723.99,762.67,"2,971.31",608.28,"4,520.71",651.59,"18,139.99","10,859.79","3,257.94"
4,8,Miguel Dionicio Luna,"27,315.62",1366,2018-01-09,910.52,966.86,"4,166.62",780.54,"5,597.13",819.47,"22,368.46","13,657.81","4,552.60"
5,9,José Manuel Franco González,"38,020.36",1500,2015-07-09,"1,267.35","1,349.38","6,599.68","1,103.24","7,613.67","1,140.61","30,317.44","19,010.18","6,970.40"
6,11,Ana Gómez Gallardo Aguilar,"82,484.98",1500,2018-02-01,"2,749.50","2,405.50","19,212.48","1,994.18","13,181.18","2,474.55","61,278.32","41,242.49","13,747.50"
7,12,Juan Manuel González Barajas,"177,157.22",1500,2018-11-05,"5,905.24","2,405.50","50,314.06","1,994.18","13,181.18","5,314.72","124,848.98","88,578.61","29,526.20"
8,13,Gerardo González Flores,"21,719.58",1086,2019-09-02,723.99,762.67,"2,971.31",608.28,"4,520.71",651.59,"18,139.99","10,859.79","3,257.94"
9,14,Mónica González Garduño,"20,481.40",1024,2018-01-24,682.71,720.12,"2,706.83",572.39,"4,296.44",614.44,"17,202.18","10,240.70","3,413.57"
10,15,Ana Paula Gout Martinez De Velasco,"47,275.96",1500,2018-09-17,"1,575.87","1,673.07","8,776.60","1,376.30","9,320.05","1,418.28","37,123.06","23,637.98","7,879.33"
11,18,Rosa Juarez Pinzon,"22,960.82",1148,2019-06-17,765.36,806.25,"3,236.43",645.05,"4,750.47",688.82,"19,079.34","11,480.41","3,444.12"
12,19,Karen Alejandra Lara Paz,"26,059.80",1303,2019-06-17,868.66,919.44,"3,898.38",740.54,"5,347.19",781.79,"21,420.88","13,029.90","3,908.97"
13,21,Adela Marín Castillo,"34,620.44",1500,2015-07-01,"1,154.01","1,229.69","5,800.02","1,002.26","6,982.70","1,038.61","27,818.16","17,310.22","6,347.08"
14,23,Samantha Itzel Martinez Narcizo,"25,931.50",1297,2019-06-17,864.38,914.74,"3,870.97",736.57,"5,322.38",777.94,"21,323.96","12,965.75","3,889.72"
15,24,Manuel Alejandro Monroy Cruz,"21,718.36",1086,2019-11-01,723.95,762.63,"2,971.04",608.25,"4,520.49",651.55,"18,139.07","10,859.18","3,257.75"
16,25,Sergio Alberto Moreno González,"27,951.88",1398,2019-06-03,931.73,989.01,"4,302.52",799.23,"5,713.91",838.56,"22,850.13","13,975.94","4,192.78"
17,26,Ricardo Neri Vázquez,"16,144.52",807,2016-01-16,538.15,568.38,"1,780.47",444.38,"3,496.51",484.34,"13,919.67","8,072.26","2,959.83"
18,27,Stephany Peniche Ake,"20,480.18",1024,2019-06-17,682.67,719.15,"2,706.57",571.58,"4,291.32",614.41,"17,202.03","10,240.09","3,072.03"
19,28,Andrés Peña Peralta,"39,985.42",1500,2015-06-01,"1,332.85","1,418.55","7,061.87","1,161.59","7,978.32","1,199.56","31,761.96","19,992.71","7,330.66"
20,29,Francisco Javier Perez Gaspar,"20,480.18",1024,2019-06-17,682.67,719.15,"2,706.57",571.58,"4,291.32",614.41,"17,202.03","10,240.09","3,072.03"
21,30,Ángel Manuel Ramírez Contreras,"30,540.14",1500,2013-11-01,"1,018.00","1,086.04","4,855.38",881.08,"6,225.42",916.20,"24,803.68","15,270.07","5,599.03"
22,31,Nayeli Melisa Rodriguez Leonardo,"29,228.38",1461,2018-11-05,974.28,"1,037.24","4,575.18",839.92,"5,968.18",876.85,"23,813.28","14,614.19","4,871.40"
23,33,Jose Maria Sandoval Torres,"22,960.82",1148,2019-06-17,765.36,806.25,"3,236.43",645.05,"4,750.47",688.82,"19,079.34","11,480.41","3,444.12"
24,35,Elias Ebeth Teco Sánchez,"38,700.42",1500,2016-06-27,"1,290.01","1,373.32","6,759.63","1,123.43","7,739.86","1,161.01","30,817.36","19,350.21","7,095.08"
25,36,María Alejandra Torres Sandoval,"35,980.22",1500,2014-01-20,"1,199.34","1,277.55","6,119.84","1,042.64","7,235.03","1,079.41","28,817.74","17,990.11","6,596.37"
26,38,Ana Norely Flores Robles,"21,098.82",1055,2020-07-13,703.29,739.90,"2,838.71",589.08,"4,400.71",632.96,"17,671.03","10,549.41","2,813.18"
27,40,Ismael Martinez Gallegos,"46,969.82",1500,2020-10-08,"1,565.66","1,658.01","8,704.60","1,363.60","9,240.68","1,409.09","36,901.62","23,484.91","6,262.64"
28,41,Margaux Andree B Jacquemin X,"27,315.62",1366,2018-01-16,910.52,966.86,"4,166.62",780.54,"5,597.13",819.47,"22,368.46","13,657.81","4,552.60"
29,42,Rogelio Cervantes Moreno,"29,228.38",1461,2019-06-16,974.28,"1,035.90","4,575.18",838.78,"5,961.11",876.85,"23,814.42","14,614.19","4,384.26"
30,43,Sarai Rosas Trujillo,"42,092.14",1500,2019-01-07,"1,403.07","1,488.89","7,557.37","1,220.92","8,349.10","1,262.76","33,313.85","21,046.07","6,313.82"
31,44,Ethel Edith Montoya Crespo,"22,960.82",1148,2019-06-17,765.36,806.25,"3,236.43",645.05,"4,750.47",688.82,"19,079.34","11,480.41","3,444.12"
32,46,Susana Garza Leon,"18,619.40",931,2021-07-01,620.65,652.11,"2,309.11",515.02,"3,937.88",558.58,"15,795.27","9,309.70","2,172.26"
33,48,Brenda Bernaldez Ruiz,"82,484.32",1500,2017-12-11,"2,749.48","2,405.50","19,212.28","1,994.18","13,181.18","2,474.53","61,277.86","41,242.16","15,122.13"
34,49,Tania Alejandra Lopez Conde Cervantes,"34,616.78",1500,2019-02-01,"1,153.89","1,226.40","5,799.16",999.49,"6,965.34","1,038.50","27,818.13","17,308.39","5,192.52"
35,50,Zurisadai Arano Rivera,"26,685.42",1334,2019-05-27,889.51,942.44,"4,032.01",759.94,"5,468.41",800.56,"21,893.47","13,342.71","4,002.81"
36,51,Maria Del Pilar Velez Jimenez,"25,442.68",1272,2020-08-01,848.09,895.58,"3,766.56",720.41,"5,221.41",763.28,"20,955.71","12,721.34","3,392.36"
37,52,Blanca Elena Leiva Lopez,"25,442.68",1272,2020-09-01,848.09,895.58,"3,766.56",720.41,"5,221.41",763.28,"20,955.71","12,721.34","3,392.36"
38,53,Ricardo Chavez Rebolledo,"29,225.34",1461,2021-09-01,974.18,"1,033.12","4,574.54",836.44,"5,946.45",876.76,"23,814.36","14,612.67","3,409.62"
39,55,Josué Leon Morales,"19,238.94",962,2022-01-16,641.30,672.92,"2,441.44",532.57,"4,047.59",577.17,"16,264.93","9,619.47","1,923.89"
40,56,Elías Trinidad Ramos Razo,"16,757.70",838,2022-02-01,558.59,586.14,"1,911.45",459.37,"3,590.12",502.73,"14,386.88","8,378.85","1,675.77"
41,57,Mariana Ramírez Castillo,"18,616.36",931,2022-02-01,620.55,651.15,"2,308.46",514.21,"3,932.80",558.49,"15,793.69","9,308.18","1,861.64"
42,58,Estela Herrera González,"56,208.08",1500,2022-02-18,"1,873.60","1,976.86","11,329.41","1,632.58","10,921.51","1,686.24","43,246.09","28,104.04","5,620.81"
43,59,Rosa Isela Gallegos Orozco,"5,255.24",263,2022-03-01,175.17,183.81,-21.96,132.71,"1,450.62",157.66,"5,144.49","2,627.62",525.52
44,60,Maria Del Carmen Tamayo Sanchez Mejorada,"17,687.64",884,2022-05-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
45,61,Monica Alvarado Espindola,"17,687.64",884,2022-05-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
46,62,Dulce Nelida Martinez Ruvalcaba,"17,687.64",884,2022-06-01,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
47,63,Brenda Hernandez Jimenez,"17,687.64",884,2022-06-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
48,64,Katya Del Rocío López Ramírez,"17,687.64",884,2022-06-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
49,65,José Alfredo López Madrigal,"17,687.64",884,2022-06-16,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
50,66,Jesus Geovanni Ruvalcaba Mota,"17,687.64",884,2022-07-01,589.59,618.67,"2,110.08",486.81,"3,761.61",530.63,"15,090.75","8,843.82","1,768.76"
51,67,Luis Manuel Guerrero Alcantara,"21,717.75",1086,2022-08-22,723.92,759.62,"2,970.91",605.72,"4,504.68",651.53,"18,141.12","10,858.88","2,171.77"
52,68,Shaila Barradas Santiago,"18,616.36",931,2022-09-19,620.55,651.15,"2,308.46",514.21,"3,932.80",558.49,"15,793.69","9,308.18","1,861.64"
53,69,Sergio Alexis Bautista Ángeles,"31,887.10",1500,2022-12-01,"1,062.90","1,126.18","5,157.14",914.94,"6,437.02",956.61,"25,815.02","15,943.55","3,188.71"