In [1]:
import pandas as pd
from cuotasimss import CuotasImss
from imss import CalculoIMSSObrero, CalculoIMSSPatron
from isr import ISR
from datetime import datetime
from sbc import SBC
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
df = pd.read_excel('./data/plantilla_laboral2.xlsx', sheet_name='Hoja1') #2022-10-27 incremento
df.head()

   Id                            Nombre  Sueldo mensual  Vales Fecha Ingreso
0   1      Martha Rosa Alvarez Martínez       33,256.68   1500    2019-06-03
1   2  Tania Monserrat Bañuelos Murillo       25,931.50   1297    2019-06-17
2   6        Karla Berenice Cano Garcia       22,960.82   1148    2019-07-23
3   7     Jonathan Covarrubias Sustaita       21,719.58   1086    2019-03-04
4   8              Miguel Dionicio Luna       27,315.62   1366    2018-01-09

In [3]:
df['Fecha Ingreso'] = pd.to_datetime(df['Fecha Ingreso'], format='%Y-%m-%d')

In [4]:
date_2022 = pd.to_datetime('2022/12/31')
defoult = 30.4
dias = 31
dias_b = 61

## Funciones Mensuales

In [5]:
def cuota_fija( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.cuotas_pres_especie_enf_mat_cuot()/defoult*dias

In [6]:
def excedente_patron( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.cuotas_pres_especie_enf_mat()/defoult*dias

In [7]:
def excedente_obrero(x):
    calculo = CalculoIMSSObrero()
    calculo.set_sdi(x)
    return calculo.cuotas_pres_especie_enf_mat()/defoult*dias

In [8]:
# prestación en dinero
def pd_patron( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.cuotas_pres_dinero_enf_mat()/defoult*dias

In [9]:
# prestación en dinero
def pd_obrero(x):
    calculo = CalculoIMSSObrero()
    calculo.set_sdi(x)
    return calculo.cuotas_pres_dinero_enf_mat()/defoult*dias

In [10]:
# gastos medicos y pensiones
def gmp_patron( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.gastos_medicos_pencionados()/defoult*dias

In [11]:
# gastos medicos y pensiones
def gmp_obrero(x):
    calculo = CalculoIMSSObrero()
    calculo.set_sdi(x)
    return calculo.gastos_medicos_pencionados()/defoult*dias

In [12]:
# riesgo de trabajo
def riesgo_trabajo( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.riesgo_de_trabajo()/defoult*dias

In [13]:
# invalidez y vida
def iv_patron( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.cuota_invalidez()/defoult*dias

In [14]:
# invalidez y vida
def iv_obrero(x):
    calculo = CalculoIMSSObrero()
    calculo.set_sdi(x)
    return calculo.cuota_invalidez()/defoult*dias

In [15]:
# guarderia y prestaciones sociales
def guarderia_ps( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.guarderia()/defoult*dias

## Funciones bimestrales

In [16]:
# retiro
def retiro( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.retiro()/defoult*dias_b

In [17]:
# Cesantía en Edad Avanzada y Vejez
def rcv_patron( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.cuota_cesantia_vejez()/defoult*dias_b

In [18]:
# Cesantía en Edad Avanzada y Vejez
def rcv_obrero(x):
    calculo = CalculoIMSSObrero()
    calculo.set_sdi(x)
    return calculo.cuota_cesantia_vejez()/defoult*dias_b

In [19]:
# infonavit
def infonavit_patron( x, date):
    calculo = CalculoIMSSPatron()
    calculo.set_fecha_base(date)
    calculo.set_sdi(x)
    return calculo.infonavit()/defoult*dias_b

In [20]:
df['SBC'] = df.apply(lambda x: SBC.funcion_sbc(sueldo = x['Sueldo mensual'], vales = x['Vales'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df['cuota fija'] = df.apply(lambda x: cuota_fija( x= x['SBC'], date =  date_2022), axis=1 )
df['excedente patron'] = df.apply(lambda x: excedente_patron( x= x['SBC'], date =  date_2022), axis=1 )
df['excedente obrero'] = df.apply(lambda x: excedente_obrero( x= x['SBC']), axis=1 )
df['PD patron'] = df.apply(lambda x: pd_patron( x= x['SBC'], date =  date_2022), axis=1 )
df['PD obrero'] = df.apply(lambda x: pd_obrero( x= x['SBC']), axis=1 )
df['GMP patron'] = df.apply(lambda x: gmp_patron( x= x['SBC'], date =  date_2022), axis=1 )
df['GMP obrero'] = df.apply(lambda x: gmp_obrero( x= x['SBC']), axis=1 )
df['riesgo de trabajo'] = df.apply(lambda x: riesgo_trabajo( x= x['SBC'], date =  date_2022), axis=1 )
df['IV patron'] = df.apply(lambda x: iv_patron( x= x['SBC'], date =  date_2022), axis=1 )
df['IV obrero'] = df.apply(lambda x: iv_obrero( x= x['SBC']), axis=1 )
df['Guarderia y PS'] = df.apply(lambda x: guarderia_ps( x= x['SBC'], date =  date_2022), axis=1 )

In [21]:
df

,Id,Nombre,Sueldo mensual,Vales,Fecha Ingreso,SBC,cuota fija,excedente patron,excedente obrero,PD patron,PD obrero,GMP patron,GMP obrero,riesgo de trabajo,IV patron,IV obrero,Guarderia y PS
0,1,Martha Rosa Alvarez Martínez,"33,256.68",1500,2019-06-03,"1,172.56",608.50,301.41,109.60,254.45,90.87,381.67,136.31,181.75,636.11,227.18,363.49
1,2,Tania Monserrat Bañuelos Murillo,"25,931.50",1297,2019-06-17,910.00,608.50,211.88,77.05,197.47,70.52,296.20,105.79,141.05,493.67,176.31,282.10
2,6,Karla Berenice Cano Garcia,"22,960.82",1148,2019-07-23,802.05,608.50,175.07,63.66,174.05,62.16,261.07,93.24,124.32,435.11,155.40,248.64
3,7,Jonathan Covarrubias Sustaita,"21,719.58",1086,2019-03-04,758.70,608.50,160.28,58.28,164.64,58.80,246.96,88.20,117.60,411.59,147.00,235.20
4,8,Miguel Dionicio Luna,"27,315.62",1366,2018-01-09,961.87,608.50,229.56,83.48,208.73,74.54,313.09,111.82,149.09,521.81,186.36,298.18
5,9,José Manuel Franco González,"38,020.36",1500,2015-07-09,"1,342.43",608.50,359.34,130.67,291.31,104.04,436.96,156.06,208.08,728.27,260.10,416.15
6,11,Ana Gómez Gallardo Aguilar,"82,484.32",1500,2018-02-01,"2,895.92",608.50,721.84,262.49,521.99,186.43,782.99,279.64,372.85,"1,304.98",466.07,745.71
7,12,Juan Manuel González Barajas,"177,157.22",1500,2018-11-05,"6,207.31",608.50,721.84,262.49,521.99,186.43,782.99,279.64,372.85,"1,304.98",466.07,745.71
8,13,Gerardo González Flores,"21,719.58",1086,2019-09-02,758.70,608.50,160.28,58.28,164.64,58.80,246.96,88.20,117.60,411.59,147.00,235.20
9,14,Mónica González Garduño,"20,481.40",1024,2018-01-24,716.38,608.50,145.85,53.04,155.46,55.52,233.18,83.28,111.04,388.64,138.80,222.08
10,15,Ana Paula Gout Martinez De Velasco,"47,275.96",1500,2018-09-17,"1,664.43",608.50,469.14,170.60,361.18,128.99,541.77,193.49,257.99,902.95,322.48,515.97
11,18,Rosa Juarez Pinzon,"22,960.82",1148,2019-06-17,802.05,608.50,175.07,63.66,174.05,62.16,261.07,93.24,124.32,435.11,155.40,248.64
12,19,Karen Alejandra Lara Paz,"26,059.80",1303,2019-06-17,914.68,608.50,213.47,77.63,198.49,70.89,297.73,106.33,141.78,496.22,177.22,283.55
13,21,Adela Marín Castillo,"34,620.44",1500,2015-07-01,"1,223.37",608.50,318.74,115.90,265.47,94.81,398.21,142.22,189.62,663.68,237.03,379.24
14,23,Samantha Itzel Martinez Narcizo,"25,931.50",1297,2019-06-17,910.00,608.50,211.88,77.05,197.47,70.52,296.20,105.79,141.05,493.67,176.31,282.10
15,24,Manuel Alejandro Monroy Cruz,"21,718.36",1086,2019-11-01,758.66,608.50,160.27,58.28,164.63,58.80,246.94,88.19,117.59,411.57,146.99,235.18
16,25,Sergio Alberto Moreno González,"27,951.88",1398,2019-06-03,983.90,608.50,237.08,86.21,213.51,76.25,320.26,114.38,152.50,533.76,190.63,305.01
17,26,Ricardo Neri Vázquez,"16,144.52",807,2016-01-16,565.43,608.50,94.38,34.32,122.70,43.82,184.05,65.73,87.64,306.75,109.55,175.28
18,27,Stephany Peniche Ake,"20,480.18",1024,2019-06-17,715.41,608.50,145.52,52.92,155.24,55.44,232.87,83.17,110.89,388.11,138.61,221.78
19,28,Andrés Peña Peralta,"39,985.42",1500,2015-06-01,"1,411.25",608.50,382.80,139.20,306.24,109.37,459.36,164.06,218.74,765.60,273.43,437.49
20,29,Francisco Javier Perez Gaspar,"20,480.18",1024,2019-06-17,715.41,608.50,145.52,52.92,155.24,55.44,232.87,83.17,110.89,388.11,138.61,221.78
21,30,Ángel Manuel Ramírez Contreras,"30,540.14",1500,2013-11-01,"1,080.46",608.50,270.00,98.18,234.46,83.74,351.69,125.60,167.47,586.15,209.34,334.94
22,31,Nayeli Melisa Rodriguez Leonardo,"29,228.38",1461,2018-11-05,"1,031.90",608.50,253.44,92.16,223.92,79.97,335.88,119.96,159.94,559.81,199.93,319.89
23,33,Jose Maria Sandoval Torres,"22,960.82",1148,2019-06-17,802.05,608.50,175.07,63.66,174.05,62.16,261.07,93.24,124.32,435.11,155.40,248.64
24,35,Elias Ebeth Teco Sánchez,"38,700.42",1500,2016-06-27,"1,366.25",608.50,367.46,133.62,296.48,105.88,444.71,158.83,211.77,741.19,264.71,423.54
25,36,María Alejandra Torres Sandoval,"35,980.22",1500,2014-01-20,"1,270.98",608.50,334.97,121.81,275.80,98.50,413.71,147.75,197.00,689.51,246.25,394.01
26,38,Ana Norely Flores Robles,"21,098.82",1055,2020-07-13,736.04,608.50,152.56,55.48,159.72,57.04,239.58,85.57,114.09,399.30,142.61,228.17
27,40,Ismael Martinez Gallegos,"46,969.82",1500,2020-10-08,"1,649.43",608.50,464.02,168.74,357.93,127.83,536.89,191.75,255.66,894.82,319.58,511.32
28,41,Margaux Andree B Jacquemin X,"27,315.62",1366,2018-01-16,961.87,608.50,229.56,83.48,208.73,74.54,313.09,111.82,149.09,521.81,186.36,298.18
29,42,Rogelio Cervantes Moreno,"29,228.38",1461,2019-06-16,"1,030.56",608.50,252.99,92.00,223.63,79.87,335.45,119.80,159.74,559.08,199.67,319.47
30,43,Sarai Rosas Trujillo,"42,092.14",1500,2019-01-07,"1,481.20",608.50,406.65,147.87,321.42,114.79,482.13,172.19,229.59,803.55,286.98,459.17
31,44,Ethel Edith Montoya Crespo,"22,960.82",1148,2019-06-17,802.05,608.50,175.07,63.66,174.05,62.16,261.07,93.24,124.32,435.11,155.40,248.64
32,46,Susana Garza Leon,"18,619.40",931,2021-07-01,648.71,608.50,122.78,44.65,140.77,50.27,211.15,75.41,100.55,351.92,125.69,201.10
33,48,Brenda Bernaldez Ruiz,"82,484.32",1500,2017-12-11,"2,899.68",608.50,721.84,262.49,521.99,186.43,782.99,279.64,372.85,"1,304.98",466.07,745.71
34,49,Tania Alejandra Lopez Conde Cervantes,"34,616.78",1500,2019-02-01,"1,220.07",608.50,317.61,115.49,264.75,94.56,397.13,141.83,189.11,661.89,236.39,378.22
35,50,Zurisadai Arano Rivera,"26,685.42",1334,2019-05-27,937.56,608.50,221.27,80.46,203.45,72.66,305.18,108.99,145.32,508.62,181.65,290.64
36,51,Maria Del Pilar Velez Jimenez,"25,442.68",1272,2020-08-01,890.94,608.50,205.38,74.68,193.33,69.05,290.00,103.57,138.10,483.34,172.62,276.19
37,52,Blanca Elena Leiva Lopez,"25,442.68",1272,2020-09-01,890.94,608.50,205.38,74.68,193.33,69.05,290.00,103.57,138.10,483.34,172.62,276.19
38,53,Ricardo Chavez Rebolledo,"29,225.34",1461,2021-09-01,"1,027.78",608.50,252.04,91.65,223.03,79.65,334.54,119.48,159.31,557.57,199.13,318.61
39,55,Josué Leon Morales,"19,238.94",962,2022-01-16,670.29,608.50,130.14,47.32,145.45,51.95,218.18,77.92,103.89,363.63,129.87,207.79
40,56,Elías Trinidad Ramos Razo,"16,757.70",838,2022-02-01,583.85,608.50,100.66,36.60,126.70,45.25,190.04,67.87,90.50,316.74,113.12,180.99
41,57,Mariana Ramírez Castillo,"18,616.36",931,2022-02-01,648.60,608.50,122.74,44.63,140.75,50.27,211.12,75.40,100.53,351.86,125.67,201.06
42,58,Estela Herrera González,"56,208.08",1500,2022-02-18,"1,969.16",608.50,573.05,208.38,427.31,152.61,640.96,228.91,305.22,"1,068.27",381.52,610.44
43,59,Rosa Isela Gallegos Orozco,"5,255.24",263,2022-03-01,183.09,608.50,0.00,0.00,39.73,14.19,59.60,21.28,28.38,99.33,35.47,56.76
44,60,Maria Del Carmen Tamayo Sanchez Mejorada,"17,687.64",884,2022-05-16,616.24,608.50,111.70,40.62,133.72,47.76,200.59,71.64,95.52,334.31,119.40,191.03
45,61,Monica Alvarado Espindola,"17,687.64",884,2022-05-16,616.24,608.50,111.70,40.62,133.72,47.76,200.59,71.64,95.52,334.31,119.40,191.03
46,62,Dulce Nelida Martinez Ruvalcaba,"17,687.64",884,2022-06-01,616.24,608.50,111.70,40.62,133.72,47.76,200.59,71.64,95.52,334.31,119.40,191.03
47,63,Brenda Hernandez Jimenez,"17,687.64",884,2022-06-16,616.24,608.50,111.70,40.62,133.72,47.76,200.59,71.64,95.52,334.31,119.40,191.03
48,64,Katya Del Rocío López Ramírez,"17,687.64",884,2022-06-16,616.24,608.50,111.70,40.62,133.72,47.76,200.59,71.64,95.52,334.31,119.40,191.03
49,65,José Alfredo López Madrigal,"17,687.64",884,2022-06-16,616.24,608.50,111.70,40.62,133.72,47.76,200.59,71.64,95.52,334.31,119.40,191.03
50,66,Jesus Geovanni Ruvalcaba Mota,"17,687.64",884,2022-07-01,616.24,608.50,111.70,40.62,133.72,47.76,200.59,71.64,95.52,334.31,119.40,191.03
51,67,Luis Manuel Guerrero Alcantara,"19,500.08",975,2022-08-22,679.38,608.50,133.24,48.45,147.43,52.65,221.14,78.98,105.30,368.57,131.63,210.61
52,68,Shaila Barradas Santiago,"18,616.36",931,2022-09-19,648.60,608.50,122.74,44.63,140.75,50.27,211.12,75.40,100.53,351.86,125.67,201.06
53,69,Sergio Alexis Bautista Ángeles,"31,887.10",1500,2022-12-01,"1,121.81",608.50,284.10,103.31,243.43,86.94,365.15,130.41,173.88,608.58,217.35,347.76

In [22]:
df_b = pd.read_excel('./data/plantilla_laboral2.xlsx', sheet_name='Hoja1') #2022-10-27 incremento
df_b['Fecha Ingreso'] = pd.to_datetime(df_b['Fecha Ingreso'], format='%Y-%m-%d')
df_b.tail()

    Id                          Nombre  Sueldo mensual  Vales Fecha Ingreso
49  65     José Alfredo López Madrigal       17,687.64    884    2022-06-16
50  66   Jesus Geovanni Ruvalcaba Mota       17,687.64    884    2022-07-01
51  67  Luis Manuel Guerrero Alcantara       19,500.08    975    2022-08-22
52  68        Shaila Barradas Santiago       18,616.36    931    2022-09-19
53  69  Sergio Alexis Bautista Ángeles       31,887.10   1500    2022-12-01

In [23]:
df_b['SBC'] = df_b.apply(lambda x: SBC.funcion_sbc(sueldo = x['Sueldo mensual'], vales = x['Vales'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df_b['retiro'] = df_b.apply(lambda x: retiro( x= x['SBC'], date =  date_2022), axis=1 )
df_b['RCV patron'] = df_b.apply(lambda x: rcv_patron( x= x['SBC'], date =  date_2022), axis=1 )
df_b['RCV obrero'] = df_b.apply(lambda x: rcv_obrero( x= x['SBC']), axis=1 )
df_b['aportación patron'] = df_b.apply(lambda x: infonavit_patron( x= x['SBC'], date =  date_2022), axis=1 )

In [24]:
df_b

,Id,Nombre,Sueldo mensual,Vales,Fecha Ingreso,SBC,retiro,RCV patron,RCV obrero,aportación patron
0,1,Martha Rosa Alvarez Martínez,"33,256.68",1500,2019-06-03,"1,172.56","1,430.52","2,253.07",804.67,"3,576.31"
1,2,Tania Monserrat Bañuelos Murillo,"25,931.50",1297,2019-06-17,910.00,"1,110.20","1,748.56",624.49,"2,775.50"
2,6,Karla Berenice Cano Garcia,"22,960.82",1148,2019-07-23,802.05,978.50,"1,541.14",550.41,"2,446.26"
3,7,Jonathan Covarrubias Sustaita,"21,719.58",1086,2019-03-04,758.70,925.61,"1,457.83",520.66,"2,314.03"
4,8,Miguel Dionicio Luna,"27,315.62",1366,2018-01-09,961.87,"1,173.48","1,848.23",660.08,"2,933.70"
5,9,José Manuel Franco González,"38,020.36",1500,2015-07-09,"1,342.43","1,637.76","2,579.48",921.24,"4,094.40"
6,11,Ana Gómez Gallardo Aguilar,"82,484.32",1500,2018-02-01,"2,895.92","2,934.71","4,622.17","1,650.77","7,336.78"
7,12,Juan Manuel González Barajas,"177,157.22",1500,2018-11-05,"6,207.31","2,934.71","4,622.17","1,650.77","7,336.78"
8,13,Gerardo González Flores,"21,719.58",1086,2019-09-02,758.70,925.61,"1,457.83",520.66,"2,314.03"
9,14,Mónica González Garduño,"20,481.40",1024,2018-01-24,716.38,873.99,"1,376.53",491.62,"2,184.96"
10,15,Ana Paula Gout Martinez De Velasco,"47,275.96",1500,2018-09-17,"1,664.43","2,030.60","3,198.20","1,142.21","5,076.50"
11,18,Rosa Juarez Pinzon,"22,960.82",1148,2019-06-17,802.05,978.50,"1,541.14",550.41,"2,446.26"
12,19,Karen Alejandra Lara Paz,"26,059.80",1303,2019-06-17,914.68,"1,115.91","1,757.56",627.70,"2,789.79"
13,21,Adela Marín Castillo,"34,620.44",1500,2015-07-01,"1,223.37","1,492.51","2,350.70",839.54,"3,731.27"
14,23,Samantha Itzel Martinez Narcizo,"25,931.50",1297,2019-06-17,910.00,"1,110.20","1,748.56",624.49,"2,775.50"
15,24,Manuel Alejandro Monroy Cruz,"21,718.36",1086,2019-11-01,758.66,925.56,"1,457.76",520.63,"2,313.91"
16,25,Sergio Alberto Moreno González,"27,951.88",1398,2019-06-03,983.90,"1,200.36","1,890.56",675.20,"3,000.90"
17,26,Ricardo Neri Vázquez,"16,144.52",807,2016-01-16,565.43,689.83,"1,086.48",388.03,"1,724.55"
18,27,Stephany Peniche Ake,"20,480.18",1024,2019-06-17,715.41,872.80,"1,374.67",490.95,"2,182.01"
19,28,Andrés Peña Peralta,"39,985.42",1500,2015-06-01,"1,411.25","1,721.73","2,711.72",968.47,"4,304.31"
20,29,Francisco Javier Perez Gaspar,"20,480.18",1024,2019-06-17,715.41,872.80,"1,374.67",490.95,"2,182.01"
21,30,Ángel Manuel Ramírez Contreras,"30,540.14",1500,2013-11-01,"1,080.46","1,318.16","2,076.10",741.46,"3,295.40"
22,31,Nayeli Melisa Rodriguez Leonardo,"29,228.38",1461,2018-11-05,"1,031.90","1,258.92","1,982.80",708.14,"3,147.30"
23,33,Jose Maria Sandoval Torres,"22,960.82",1148,2019-06-17,802.05,978.50,"1,541.14",550.41,"2,446.26"
24,35,Elias Ebeth Teco Sánchez,"38,700.42",1500,2016-06-27,"1,366.25","1,666.82","2,625.25",937.59,"4,167.06"
25,36,María Alejandra Torres Sandoval,"35,980.22",1500,2014-01-20,"1,270.98","1,550.60","2,442.20",872.21,"3,876.51"
26,38,Ana Norely Flores Robles,"21,098.82",1055,2020-07-13,736.04,897.97,"1,414.31",505.11,"2,244.94"
27,40,Ismael Martinez Gallegos,"46,969.82",1500,2020-10-08,"1,649.43","2,012.31","3,169.39","1,131.92","5,030.77"
28,41,Margaux Andree B Jacquemin X,"27,315.62",1366,2018-01-16,961.87,"1,173.48","1,848.23",660.08,"2,933.70"
29,42,Rogelio Cervantes Moreno,"29,228.38",1461,2019-06-16,"1,030.56","1,257.28","1,980.22",707.22,"3,143.21"
30,43,Sarai Rosas Trujillo,"42,092.14",1500,2019-01-07,"1,481.20","1,807.06","2,846.12","1,016.47","4,517.65"
31,44,Ethel Edith Montoya Crespo,"22,960.82",1148,2019-06-17,802.05,978.50,"1,541.14",550.41,"2,446.26"
32,46,Susana Garza Leon,"18,619.40",931,2021-07-01,648.71,791.42,"1,246.49",445.17,"1,978.55"
33,48,Brenda Bernaldez Ruiz,"82,484.32",1500,2017-12-11,"2,899.68","2,934.71","4,622.17","1,650.77","7,336.78"
34,49,Tania Alejandra Lopez Conde Cervantes,"34,616.78",1500,2019-02-01,"1,220.07","1,488.48","2,344.36",837.27,"3,721.20"
35,50,Zurisadai Arano Rivera,"26,685.42",1334,2019-05-27,937.56,"1,143.82","1,801.52",643.40,"2,859.56"
36,51,Maria Del Pilar Velez Jimenez,"25,442.68",1272,2020-08-01,890.94,"1,086.95","1,711.95",611.41,"2,717.37"
37,52,Blanca Elena Leiva Lopez,"25,442.68",1272,2020-09-01,890.94,"1,086.95","1,711.95",611.41,"2,717.37"
38,53,Ricardo Chavez Rebolledo,"29,225.34",1461,2021-09-01,"1,027.78","1,253.89","1,974.88",705.31,"3,134.72"
39,55,Josué Leon Morales,"19,238.94",962,2022-01-16,670.29,817.75,"1,287.96",459.99,"2,044.38"
40,56,Elías Trinidad Ramos Razo,"16,757.70",838,2022-02-01,583.85,712.30,"1,121.87",400.67,"1,780.74"
41,57,Mariana Ramírez Castillo,"18,616.36",931,2022-02-01,648.60,791.29,"1,246.28",445.10,"1,978.21"
42,58,Estela Herrera González,"56,208.08",1500,2022-02-18,"1,969.16","2,402.37","3,783.73","1,351.33","6,005.93"
43,59,Rosa Isela Gallegos Orozco,"5,255.24",263,2022-03-01,183.09,223.38,351.82,125.65,558.43
44,60,Maria Del Carmen Tamayo Sanchez Mejorada,"17,687.64",884,2022-05-16,616.24,751.81,"1,184.10",422.89,"1,879.52"
45,61,Monica Alvarado Espindola,"17,687.64",884,2022-05-16,616.24,751.81,"1,184.10",422.89,"1,879.52"
46,62,Dulce Nelida Martinez Ruvalcaba,"17,687.64",884,2022-06-01,616.24,751.81,"1,184.10",422.89,"1,879.52"
47,63,Brenda Hernandez Jimenez,"17,687.64",884,2022-06-16,616.24,751.81,"1,184.10",422.89,"1,879.52"
48,64,Katya Del Rocío López Ramírez,"17,687.64",884,2022-06-16,616.24,751.81,"1,184.10",422.89,"1,879.52"
49,65,José Alfredo López Madrigal,"17,687.64",884,2022-06-16,616.24,751.81,"1,184.10",422.89,"1,879.52"
50,66,Jesus Geovanni Ruvalcaba Mota,"17,687.64",884,2022-07-01,616.24,751.81,"1,184.10",422.89,"1,879.52"
51,67,Luis Manuel Guerrero Alcantara,"19,500.08",975,2022-08-22,679.38,828.85,"1,305.43",466.23,"2,072.11"
52,68,Shaila Barradas Santiago,"18,616.36",931,2022-09-19,648.60,791.29,"1,246.28",445.10,"1,978.21"
53,69,Sergio Alexis Bautista Ángeles,"31,887.10",1500,2022-12-01,"1,121.81","1,368.61","2,155.55",769.84,"3,421.52"