In [1]:
import pandas as pd
from cuotasimss import CuotasImss
from imss import CalculoIMSSObrero, CalculoIMSSPatron
from isr import ISR
from datetime import datetime
from sbc import SBC
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
df = pd.read_excel('./data/plantilla_laboral2.xlsx', sheet_name='Hoja1') #2022-10-27 incremento
df.head()

   Id                            Nombre  Sueldo mensual  Vales Fecha Ingreso
0   1      Martha Rosa Alvarez Martínez       33,256.68   1500    2019-06-03
1   2  Tania Monserrat Bañuelos Murillo       25,931.50   1297    2019-06-17
2   6        Karla Berenice Cano Garcia       22,960.82   1148    2019-07-23
3   7     Jonathan Covarrubias Sustaita       21,719.58   1086    2019-03-04
4   8              Miguel Dionicio Luna       27,315.62   1366    2018-01-09

In [3]:
df['Fecha Ingreso'] = pd.to_datetime(df['Fecha Ingreso'], format='%Y-%m-%d')

In [4]:
date_2022 = pd.to_datetime('2023/12/31')
date_ = pd.to_datetime('2023/12/31')

In [5]:
df['SD'] = df['Sueldo mensual'].apply(lambda x: x / 30)
df['SBC'] = df.apply(lambda x: SBC.funcion_sbc(sueldo = x['Sueldo mensual'], vales = x['Vales'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df['ISR'] = (df['Sueldo mensual'] * 1).apply(lambda x: ISR.function_isr(x))
df['IMSS_Ob'] = df['SBC'].apply(lambda x: CalculoIMSSObrero.function_imss_obrero(x))
df['IMSS_Pt'] = df.apply(lambda x: CalculoIMSSPatron.function_imss_patronal(x = x['SBC'], date=date_ ), axis=1)
df['ISN'] = df['Sueldo mensual'] * 0.03
_isr_ = df['Sueldo mensual'].apply(lambda x: ISR.function_isr(x))
df['Neto'] = df['Sueldo mensual'] - _isr_ - df['IMSS_Ob']
df['Aguinaldo'] = df.apply(lambda x: SBC.funcion_aguinaldo(sueldo = x['Sueldo mensual'], a = x['Fecha Ingreso'], b = date_2022), axis=1)
df['Prima Vacacional'] = df.apply(lambda x: SBC.funcion_pv(sueldo = x['Sueldo mensual'], date_ingreso = x['Fecha Ingreso'], date_base = date_2022), axis=1)

In [6]:
df

,Id,Nombre,Sueldo mensual,Vales,Fecha Ingreso,SD,SBC,ISR,IMSS_Ob,IMSS_Pt,ISN,Neto,Aguinaldo,Prima Vacacional
0,1,Martha Rosa Alvarez Martínez,"33,256.68",1500,2019-06-03,"1,108.56","1,178.64","5,797.85",959.20,"6,713.58",997.70,"26,499.63","16,628.34","4,988.50"
1,2,Tania Monserrat Bañuelos Murillo,"25,931.50",1297,2019-06-17,864.38,914.74,"4,097.80",736.57,"5,322.38",777.94,"21,097.13","12,965.75","3,889.72"
2,6,Karla Berenice Cano Garcia,"22,960.82",1148,2019-07-23,765.36,806.25,"3,463.27",645.05,"4,750.47",688.82,"18,852.50","11,480.41","3,444.12"
3,7,Jonathan Covarrubias Sustaita,"21,719.58",1086,2019-03-04,723.99,762.67,"3,198.14",608.28,"4,520.71",651.59,"17,913.16","10,859.79","3,257.94"
4,8,Miguel Dionicio Luna,"27,315.62",1366,2018-01-09,910.52,966.86,"4,400.52",780.54,"5,597.13",819.47,"22,134.56","13,657.81","4,552.60"
5,9,José Manuel Franco González,"38,020.36",1500,2015-07-09,"1,267.35","1,349.38","6,918.27","1,103.24","7,613.67","1,140.61","29,998.85","19,010.18","6,970.40"
6,11,Ana Gómez Gallardo Aguilar,"82,484.98",1500,2018-02-01,"2,749.50","2,911.00","19,990.42","1,994.18","13,181.18","2,474.55","60,500.38","41,242.49","13,747.50"
7,12,Juan Manuel González Barajas,"177,157.22",1500,2018-11-05,"5,905.24","6,239.66","51,663.04","1,994.18","13,181.18","5,314.72","123,500.00","88,578.61","29,526.20"
8,13,Gerardo González Flores,"21,719.58",1086,2019-09-02,723.99,762.67,"3,198.14",608.28,"4,520.71",651.59,"17,913.16","10,859.79","3,257.94"
9,14,Mónica González Garduño,"20,481.40",1024,2018-01-24,682.71,720.12,"2,933.66",572.39,"4,296.44",614.44,"16,975.35","10,240.70","3,413.57"
10,15,Ana Paula Gout Martinez De Velasco,"47,275.96",1500,2018-09-17,"1,575.87","1,673.07","9,402.24","1,376.30","9,320.05","1,418.28","36,497.42","23,637.98","7,879.33"
11,18,Rosa Juarez Pinzon,"22,960.82",1148,2019-06-17,765.36,806.25,"3,463.27",645.05,"4,750.47",688.82,"18,852.50","11,480.41","3,444.12"
12,19,Karen Alejandra Lara Paz,"26,059.80",1303,2019-06-17,868.66,919.44,"4,125.21",740.54,"5,347.19",781.79,"21,194.05","13,029.90","3,908.97"
13,21,Adela Marín Castillo,"34,620.44",1500,2015-07-01,"1,154.01","1,229.69","6,118.61","1,002.26","6,982.70","1,038.61","27,499.57","17,310.22","6,347.08"
14,23,Samantha Itzel Martinez Narcizo,"25,931.50",1297,2019-06-17,864.38,914.74,"4,097.80",736.57,"5,322.38",777.94,"21,097.13","12,965.75","3,889.72"
15,24,Manuel Alejandro Monroy Cruz,"21,718.36",1086,2019-11-01,723.95,762.63,"3,197.88",608.25,"4,520.49",651.55,"17,912.23","10,859.18","3,257.75"
16,25,Sergio Alberto Moreno González,"27,951.88",1398,2019-06-03,931.73,989.01,"4,550.16",799.23,"5,713.91",838.56,"22,602.49","13,975.94","4,192.78"
17,26,Ricardo Neri Vázquez,"16,144.52",807,2016-01-16,538.15,568.38,"2,007.31",444.38,"3,496.51",484.34,"13,692.83","8,072.26","2,959.83"
18,27,Stephany Peniche Ake,"20,480.18",1024,2019-06-17,682.67,719.15,"2,933.40",571.58,"4,291.32",614.41,"16,975.20","10,240.09","3,072.03"
19,28,Andrés Peña Peralta,"39,985.42",1500,2015-06-01,"1,332.85","1,418.55","7,380.45","1,161.59","7,978.32","1,199.56","31,443.38","19,992.71","7,330.66"
20,29,Francisco Javier Perez Gaspar,"20,480.18",1024,2019-06-17,682.67,719.15,"2,933.40",571.58,"4,291.32",614.41,"16,975.20","10,240.09","3,072.03"
21,30,Ángel Manuel Ramírez Contreras,"30,540.14",1500,2013-11-01,"1,018.00","1,086.04","5,158.92",881.08,"6,225.42",916.20,"24,500.14","15,270.07","5,599.03"
22,31,Nayeli Melisa Rodriguez Leonardo,"29,228.38",1461,2018-11-05,974.28,"1,037.24","4,850.40",839.92,"5,968.18",876.85,"23,538.06","14,614.19","4,871.40"
23,33,Jose Maria Sandoval Torres,"22,960.82",1148,2019-06-17,765.36,806.25,"3,463.27",645.05,"4,750.47",688.82,"18,852.50","11,480.41","3,444.12"
24,35,Elias Ebeth Teco Sánchez,"38,700.42",1500,2016-06-27,"1,290.01","1,373.32","7,078.22","1,123.43","7,739.86","1,161.01","30,498.77","19,350.21","7,095.08"
25,36,María Alejandra Torres Sandoval,"35,980.22",1500,2014-01-20,"1,199.34","1,277.55","6,438.43","1,042.64","7,235.03","1,079.41","28,499.15","17,990.11","6,596.37"
26,38,Ana Norely Flores Robles,"21,098.82",1055,2020-07-13,703.29,739.90,"3,065.54",589.08,"4,400.71",632.96,"17,444.20","10,549.41","2,813.18"
27,40,Ismael Martinez Gallegos,"46,969.82",1500,2020-10-08,"1,565.66","1,658.01","9,310.40","1,363.60","9,240.68","1,409.09","36,295.82","23,484.91","6,262.64"
28,41,Margaux Andree B Jacquemin X,"27,315.62",1366,2018-01-16,910.52,966.86,"4,400.52",780.54,"5,597.13",819.47,"22,134.56","13,657.81","4,552.60"
29,42,Rogelio Cervantes Moreno,"29,228.38",1461,2019-06-16,974.28,"1,035.90","4,850.40",838.78,"5,961.11",876.85,"23,539.20","14,614.19","4,384.26"
30,43,Sarai Rosas Trujillo,"42,092.14",1500,2019-01-07,"1,403.07","1,488.89","7,875.95","1,220.92","8,349.10","1,262.76","32,995.27","21,046.07","6,313.82"
31,44,Ethel Edith Montoya Crespo,"22,960.82",1148,2019-06-17,765.36,806.25,"3,463.27",645.05,"4,750.47",688.82,"18,852.50","11,480.41","3,444.12"
32,46,Susana Garza Leon,"18,619.40",931,2021-07-01,620.65,652.11,"2,535.94",515.02,"3,937.88",558.58,"15,568.44","9,309.70","2,172.26"
33,48,Brenda Bernaldez Ruiz,"82,484.32",1500,2017-12-11,"2,749.48","2,914.75","19,990.21","1,994.18","13,181.18","2,474.53","60,499.93","41,242.16","15,122.13"
34,49,Tania Alejandra Lopez Conde Cervantes,"34,616.78",1500,2019-02-01,"1,153.89","1,226.40","6,117.75",999.49,"6,965.34","1,038.50","27,499.54","17,308.39","5,192.52"
35,50,Zurisadai Arano Rivera,"26,685.42",1334,2019-05-27,889.51,942.44,"4,258.84",759.94,"5,468.41",800.56,"21,666.64","13,342.71","4,002.81"
36,51,Maria Del Pilar Velez Jimenez,"25,442.68",1272,2020-08-01,848.09,895.58,"3,993.39",720.41,"5,221.41",763.28,"20,728.88","12,721.34","3,392.36"
37,52,Blanca Elena Leiva Lopez,"25,442.68",1272,2020-09-01,848.09,895.58,"3,993.39",720.41,"5,221.41",763.28,"20,728.88","12,721.34","3,392.36"
38,53,Ricardo Chavez Rebolledo,"29,225.34",1461,2021-09-01,974.18,"1,033.12","4,849.68",836.44,"5,946.45",876.76,"23,539.22","14,612.67","3,409.62"
39,55,Josué Leon Morales,"19,238.94",962,2022-01-16,641.30,672.92,"2,668.27",532.57,"4,047.59",577.17,"16,038.10","9,619.47","1,923.89"
40,56,Elías Trinidad Ramos Razo,"16,757.70",838,2022-02-01,558.59,586.14,"2,138.28",459.37,"3,590.12",502.73,"14,160.05","8,378.85","1,675.77"
41,57,Mariana Ramírez Castillo,"18,616.36",931,2022-02-01,620.55,651.15,"2,535.29",514.21,"3,932.80",558.49,"15,566.86","9,308.18","1,861.64"
42,58,Estela Herrera González,"56,208.08",1500,2022-02-18,"1,873.60","1,976.86","12,081.88","1,632.58","10,921.51","1,686.24","42,493.62","28,104.04","5,620.81"
43,59,Rosa Isela Gallegos Orozco,"5,255.24",263,2022-03-01,175.17,183.81,-17.41,132.71,"1,450.62",157.66,"5,139.94","2,627.62",525.52
44,60,Maria Del Carmen Tamayo Sanchez Mejorada,"17,687.64",884,2022-05-16,589.59,618.67,"2,336.92",486.81,"3,761.61",530.63,"14,863.91","8,843.82","1,768.76"
45,61,Monica Alvarado Espindola,"17,687.64",884,2022-05-16,589.59,618.67,"2,336.92",486.81,"3,761.61",530.63,"14,863.91","8,843.82","1,768.76"
46,62,Dulce Nelida Martinez Ruvalcaba,"17,687.64",884,2022-06-01,589.59,618.67,"2,336.92",486.81,"3,761.61",530.63,"14,863.91","8,843.82","1,768.76"
47,63,Brenda Hernandez Jimenez,"17,687.64",884,2022-06-16,589.59,618.67,"2,336.92",486.81,"3,761.61",530.63,"14,863.91","8,843.82","1,768.76"
48,64,Katya Del Rocío López Ramírez,"17,687.64",884,2022-06-16,589.59,618.67,"2,336.92",486.81,"3,761.61",530.63,"14,863.91","8,843.82","1,768.76"
49,65,José Alfredo López Madrigal,"17,687.64",884,2022-06-16,589.59,618.67,"2,336.92",486.81,"3,761.61",530.63,"14,863.91","8,843.82","1,768.76"
50,66,Jesus Geovanni Ruvalcaba Mota,"17,687.64",884,2022-07-01,589.59,618.67,"2,336.92",486.81,"3,761.61",530.63,"14,863.91","8,843.82","1,768.76"
51,67,Luis Manuel Guerrero Alcantara,"21,717.75",1086,2022-08-22,723.92,759.62,"3,197.75",605.72,"4,504.68",651.53,"17,914.28","10,858.88","2,171.77"
52,68,Shaila Barradas Santiago,"18,616.36",931,2022-09-19,620.55,651.15,"2,535.29",514.21,"3,932.80",558.49,"15,566.86","9,308.18","1,861.64"
53,69,Sergio Alexis Bautista Ángeles,"31,887.10",1500,2022-12-01,"1,062.90","1,126.18","5,475.73",914.94,"6,437.02",956.61,"25,496.43","15,943.55","3,188.71"

In [ ]:
df.head()

In [ ]:
df.tail(5)

In [ ]:
df.query('Nombre.str.contains("Rogelio")', engine='python')

In [ ]:
calculo = df.query('Nombre.str.contains("Sergio")', engine='python')

In [ ]:
calculo.T

In [ ]:
df.to_excel('./resultados/calculos_2023_sin_cambio_IMSS_12_dias.xlsx', index=False, sheet_name='2023-12-31')

In [ ]:
df.query('Nombre.str.contains("Ana Gómez")', engine='python').T